// Code generated by protoc-gen-go-extension. DO NOT EDIT.

package initv1

import (
	api "github.com/openkcm/plugin-sdk/api"
	grpc "google.golang.org/grpc"
)

const (
	GRPCServiceFullName = "service.init.v1.Bootstrap"
)

func BootstrapServiceServer(server BootstrapServer) api.ServiceServer {
	return bootstrapServiceServer{BootstrapServer: server}
}

type bootstrapServiceServer struct {
	BootstrapServer
}

func (s bootstrapServiceServer) GRPCServiceName() string {
	return GRPCServiceFullName
}

func (s bootstrapServiceServer) RegisterServer(server *grpc.Server) any {
	RegisterBootstrapServer(server, s.BootstrapServer)
	return s.BootstrapServer
}

type BootstrapServiceClient struct {
	BootstrapClient
}

func (c *BootstrapServiceClient) IsInitialized() bool {
	return c.BootstrapClient != nil
}

func (c *BootstrapServiceClient) GRPCServiceName() string {
	return GRPCServiceFullName
}

func (c *BootstrapServiceClient) InitClient(conn grpc.ClientConnInterface) any {
	c.BootstrapClient = NewBootstrapClient(conn)
	return c.BootstrapClient
}
