// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: plugin/systeminformation/v1/systeminformation.proto

package systeminformationv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SystemInformationService_Get_FullMethodName = "/plugin.systeminformation.v1.SystemInformationService/Get"
)

// SystemInformationServiceClient is the client API for SystemInformationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SystemInformationServiceClient interface {
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
}

type systemInformationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSystemInformationServiceClient(cc grpc.ClientConnInterface) SystemInformationServiceClient {
	return &systemInformationServiceClient{cc}
}

func (c *systemInformationServiceClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, SystemInformationService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SystemInformationServiceServer is the server API for SystemInformationService service.
// All implementations must embed UnimplementedSystemInformationServiceServer
// for forward compatibility.
type SystemInformationServiceServer interface {
	Get(context.Context, *GetRequest) (*GetResponse, error)
	mustEmbedUnimplementedSystemInformationServiceServer()
}

// UnimplementedSystemInformationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSystemInformationServiceServer struct{}

func (UnimplementedSystemInformationServiceServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedSystemInformationServiceServer) mustEmbedUnimplementedSystemInformationServiceServer() {
}
func (UnimplementedSystemInformationServiceServer) testEmbeddedByValue() {}

// UnsafeSystemInformationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SystemInformationServiceServer will
// result in compilation errors.
type UnsafeSystemInformationServiceServer interface {
	mustEmbedUnimplementedSystemInformationServiceServer()
}

func RegisterSystemInformationServiceServer(s grpc.ServiceRegistrar, srv SystemInformationServiceServer) {
	// If the following call panics, it indicates UnimplementedSystemInformationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SystemInformationService_ServiceDesc, srv)
}

func _SystemInformationService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemInformationServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemInformationService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemInformationServiceServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SystemInformationService_ServiceDesc is the grpc.ServiceDesc for SystemInformationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SystemInformationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "plugin.systeminformation.v1.SystemInformationService",
	HandlerType: (*SystemInformationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _SystemInformationService_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin/systeminformation/v1/systeminformation.proto",
}
