// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: plugin/key_management/v1/key_management.proto

package key_managementv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"

	v1 "github.com/openkcm/plugin-sdk/proto/plugin/common/v1"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Algorithm defines the supported key algorithms across all operations
type Algorithm int32

const (
	Algorithm_UNKNOWN Algorithm = 0
	Algorithm_AES256  Algorithm = 1
	Algorithm_RSA3072 Algorithm = 2
	Algorithm_RSA4096 Algorithm = 3
)

// Enum value maps for Algorithm.
var (
	Algorithm_name = map[int32]string{
		0: "UNKNOWN",
		1: "AES256",
		2: "RSA3072",
		3: "RSA4096",
	}
	Algorithm_value = map[string]int32{
		"UNKNOWN": 0,
		"AES256":  1,
		"RSA3072": 2,
		"RSA4096": 3,
	}
)

func (x Algorithm) Enum() *Algorithm {
	p := new(Algorithm)
	*p = x
	return p
}

func (x Algorithm) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Algorithm) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_key_management_v1_key_management_proto_enumTypes[0].Descriptor()
}

func (Algorithm) Type() protoreflect.EnumType {
	return &file_plugin_key_management_v1_key_management_proto_enumTypes[0]
}

func (x Algorithm) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Algorithm.Descriptor instead.
func (Algorithm) EnumDescriptor() ([]byte, []int) {
	return file_plugin_key_management_v1_key_management_proto_rawDescGZIP(), []int{0}
}

type KeyType int32

const (
	KeyType_UNSPECIFIED    KeyType = 0
	KeyType_SYSTEM_MANAGED KeyType = 1 // System-managed key
	KeyType_BYOK           KeyType = 2 // Bring Your Own Key
	KeyType_HYOK           KeyType = 3 // Hold Your Own Key
)

// Enum value maps for KeyType.
var (
	KeyType_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "SYSTEM_MANAGED",
		2: "BYOK",
		3: "HYOK",
	}
	KeyType_value = map[string]int32{
		"UNSPECIFIED":    0,
		"SYSTEM_MANAGED": 1,
		"BYOK":           2,
		"HYOK":           3,
	}
)

func (x KeyType) Enum() *KeyType {
	p := new(KeyType)
	*p = x
	return p
}

func (x KeyType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KeyType) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_key_management_v1_key_management_proto_enumTypes[1].Descriptor()
}

func (KeyType) Type() protoreflect.EnumType {
	return &file_plugin_key_management_v1_key_management_proto_enumTypes[1]
}

func (x KeyType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KeyType.Descriptor instead.
func (KeyType) EnumDescriptor() ([]byte, []int) {
	return file_plugin_key_management_v1_key_management_proto_rawDescGZIP(), []int{1}
}

// RequestParameters contains the common fields needed for most key operations
type RequestParameters struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Config        *v1.KeystoreInstanceConfig `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	KeyId         string                     `protobuf:"bytes,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestParameters) Reset() {
	*x = RequestParameters{}
	mi := &file_plugin_key_management_v1_key_management_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestParameters) ProtoMessage() {}

func (x *RequestParameters) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_key_management_v1_key_management_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestParameters.ProtoReflect.Descriptor instead.
func (*RequestParameters) Descriptor() ([]byte, []int) {
	return file_plugin_key_management_v1_key_management_proto_rawDescGZIP(), []int{0}
}

func (x *RequestParameters) GetConfig() *v1.KeystoreInstanceConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *RequestParameters) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

// GetKeyRequest contains parameters for key retrieval
type GetKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parameters    *RequestParameters     `protobuf:"bytes,1,opt,name=parameters,proto3" json:"parameters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKeyRequest) Reset() {
	*x = GetKeyRequest{}
	mi := &file_plugin_key_management_v1_key_management_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeyRequest) ProtoMessage() {}

func (x *GetKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_key_management_v1_key_management_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeyRequest.ProtoReflect.Descriptor instead.
func (*GetKeyRequest) Descriptor() ([]byte, []int) {
	return file_plugin_key_management_v1_key_management_proto_rawDescGZIP(), []int{1}
}

func (x *GetKeyRequest) GetParameters() *RequestParameters {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type GetKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`                                     // The ID of the retrieved key
	Algorithm     Algorithm              `protobuf:"varint,2,opt,name=algorithm,proto3,enum=plugin.key_management.v1.Algorithm" json:"algorithm,omitempty"` // The algorithm used for the key
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`                                                // The current status of the key (e.g., enabled, disabled)
	Usage         string                 `protobuf:"bytes,4,opt,name=usage,proto3" json:"usage,omitempty"`                                                  // The intended usage of the key (e.g., encryption, signing)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKeyResponse) Reset() {
	*x = GetKeyResponse{}
	mi := &file_plugin_key_management_v1_key_management_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeyResponse) ProtoMessage() {}

func (x *GetKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_key_management_v1_key_management_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeyResponse.ProtoReflect.Descriptor instead.
func (*GetKeyResponse) Descriptor() ([]byte, []int) {
	return file_plugin_key_management_v1_key_management_proto_rawDescGZIP(), []int{2}
}

func (x *GetKeyResponse) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *GetKeyResponse) GetAlgorithm() Algorithm {
	if x != nil {
		return x.Algorithm
	}
	return Algorithm_UNKNOWN
}

func (x *GetKeyResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetKeyResponse) GetUsage() string {
	if x != nil {
		return x.Usage
	}
	return ""
}

// CreateKeyRequest contains parameters for key creation
type CreateKeyRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Config        *v1.KeystoreInstanceConfig `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	Algorithm     Algorithm                  `protobuf:"varint,2,opt,name=algorithm,proto3,enum=plugin.key_management.v1.Algorithm" json:"algorithm,omitempty"`
	Id            *string                    `protobuf:"bytes,3,opt,name=id,proto3,oneof" json:"id,omitempty"`                                                           // Optional predefined key ID
	Region        string                     `protobuf:"bytes,4,opt,name=region,proto3" json:"region,omitempty"`                                                         // The region in which to create the key
	KeyType       KeyType                    `protobuf:"varint,5,opt,name=key_type,json=keyType,proto3,enum=plugin.key_management.v1.KeyType" json:"key_type,omitempty"` // Key type (system-managed or BYOK)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateKeyRequest) Reset() {
	*x = CreateKeyRequest{}
	mi := &file_plugin_key_management_v1_key_management_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKeyRequest) ProtoMessage() {}

func (x *CreateKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_key_management_v1_key_management_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKeyRequest.ProtoReflect.Descriptor instead.
func (*CreateKeyRequest) Descriptor() ([]byte, []int) {
	return file_plugin_key_management_v1_key_management_proto_rawDescGZIP(), []int{3}
}

func (x *CreateKeyRequest) GetConfig() *v1.KeystoreInstanceConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *CreateKeyRequest) GetAlgorithm() Algorithm {
	if x != nil {
		return x.Algorithm
	}
	return Algorithm_UNKNOWN
}

func (x *CreateKeyRequest) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *CreateKeyRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *CreateKeyRequest) GetKeyType() KeyType {
	if x != nil {
		return x.KeyType
	}
	return KeyType_UNSPECIFIED
}

type CreateKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"` // The ID of the created key
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`            // The current status of the key (e.g., enabled, disabled)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateKeyResponse) Reset() {
	*x = CreateKeyResponse{}
	mi := &file_plugin_key_management_v1_key_management_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKeyResponse) ProtoMessage() {}

func (x *CreateKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_key_management_v1_key_management_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKeyResponse.ProtoReflect.Descriptor instead.
func (*CreateKeyResponse) Descriptor() ([]byte, []int) {
	return file_plugin_key_management_v1_key_management_proto_rawDescGZIP(), []int{4}
}

func (x *CreateKeyResponse) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *CreateKeyResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// DeleteKeyRequest contains parameters for key deletion
type DeleteKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parameters    *RequestParameters     `protobuf:"bytes,1,opt,name=parameters,proto3" json:"parameters,omitempty"`
	Window        *int32                 `protobuf:"varint,2,opt,name=window,proto3,oneof" json:"window,omitempty"` // Optional deletion window in days
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteKeyRequest) Reset() {
	*x = DeleteKeyRequest{}
	mi := &file_plugin_key_management_v1_key_management_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKeyRequest) ProtoMessage() {}

func (x *DeleteKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_key_management_v1_key_management_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKeyRequest.ProtoReflect.Descriptor instead.
func (*DeleteKeyRequest) Descriptor() ([]byte, []int) {
	return file_plugin_key_management_v1_key_management_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteKeyRequest) GetParameters() *RequestParameters {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *DeleteKeyRequest) GetWindow() int32 {
	if x != nil && x.Window != nil {
		return *x.Window
	}
	return 0
}

type DeleteKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteKeyResponse) Reset() {
	*x = DeleteKeyResponse{}
	mi := &file_plugin_key_management_v1_key_management_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKeyResponse) ProtoMessage() {}

func (x *DeleteKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_key_management_v1_key_management_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKeyResponse.ProtoReflect.Descriptor instead.
func (*DeleteKeyResponse) Descriptor() ([]byte, []int) {
	return file_plugin_key_management_v1_key_management_proto_rawDescGZIP(), []int{6}
}

// EnableKeyRequest contains parameters for key enablement
type EnableKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parameters    *RequestParameters     `protobuf:"bytes,1,opt,name=parameters,proto3" json:"parameters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableKeyRequest) Reset() {
	*x = EnableKeyRequest{}
	mi := &file_plugin_key_management_v1_key_management_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableKeyRequest) ProtoMessage() {}

func (x *EnableKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_key_management_v1_key_management_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableKeyRequest.ProtoReflect.Descriptor instead.
func (*EnableKeyRequest) Descriptor() ([]byte, []int) {
	return file_plugin_key_management_v1_key_management_proto_rawDescGZIP(), []int{7}
}

func (x *EnableKeyRequest) GetParameters() *RequestParameters {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type EnableKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableKeyResponse) Reset() {
	*x = EnableKeyResponse{}
	mi := &file_plugin_key_management_v1_key_management_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableKeyResponse) ProtoMessage() {}

func (x *EnableKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_key_management_v1_key_management_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableKeyResponse.ProtoReflect.Descriptor instead.
func (*EnableKeyResponse) Descriptor() ([]byte, []int) {
	return file_plugin_key_management_v1_key_management_proto_rawDescGZIP(), []int{8}
}

// DisableKeyRequest contains parameters for key disablement
type DisableKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parameters    *RequestParameters     `protobuf:"bytes,1,opt,name=parameters,proto3" json:"parameters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableKeyRequest) Reset() {
	*x = DisableKeyRequest{}
	mi := &file_plugin_key_management_v1_key_management_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableKeyRequest) ProtoMessage() {}

func (x *DisableKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_key_management_v1_key_management_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableKeyRequest.ProtoReflect.Descriptor instead.
func (*DisableKeyRequest) Descriptor() ([]byte, []int) {
	return file_plugin_key_management_v1_key_management_proto_rawDescGZIP(), []int{9}
}

func (x *DisableKeyRequest) GetParameters() *RequestParameters {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type DisableKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableKeyResponse) Reset() {
	*x = DisableKeyResponse{}
	mi := &file_plugin_key_management_v1_key_management_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableKeyResponse) ProtoMessage() {}

func (x *DisableKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_key_management_v1_key_management_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableKeyResponse.ProtoReflect.Descriptor instead.
func (*DisableKeyResponse) Descriptor() ([]byte, []int) {
	return file_plugin_key_management_v1_key_management_proto_rawDescGZIP(), []int{10}
}

// GetImportParametersRequest contains parameters for retrieving import parameters
type GetImportParametersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parameters    *RequestParameters     `protobuf:"bytes,1,opt,name=parameters,proto3" json:"parameters,omitempty"`
	Algorithm     Algorithm              `protobuf:"varint,2,opt,name=algorithm,proto3,enum=plugin.key_management.v1.Algorithm" json:"algorithm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetImportParametersRequest) Reset() {
	*x = GetImportParametersRequest{}
	mi := &file_plugin_key_management_v1_key_management_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetImportParametersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImportParametersRequest) ProtoMessage() {}

func (x *GetImportParametersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_key_management_v1_key_management_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImportParametersRequest.ProtoReflect.Descriptor instead.
func (*GetImportParametersRequest) Descriptor() ([]byte, []int) {
	return file_plugin_key_management_v1_key_management_proto_rawDescGZIP(), []int{11}
}

func (x *GetImportParametersRequest) GetParameters() *RequestParameters {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *GetImportParametersRequest) GetAlgorithm() Algorithm {
	if x != nil {
		return x.Algorithm
	}
	return Algorithm_UNKNOWN
}

// ImportKeyMaterialRequest contains parameters for importing key material
type GetImportParametersResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	KeyId            string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	ImportParameters *structpb.Struct       `protobuf:"bytes,2,opt,name=import_parameters,json=importParameters,proto3" json:"import_parameters,omitempty"` // The parameters needed for importing key material
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetImportParametersResponse) Reset() {
	*x = GetImportParametersResponse{}
	mi := &file_plugin_key_management_v1_key_management_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetImportParametersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImportParametersResponse) ProtoMessage() {}

func (x *GetImportParametersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_key_management_v1_key_management_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImportParametersResponse.ProtoReflect.Descriptor instead.
func (*GetImportParametersResponse) Descriptor() ([]byte, []int) {
	return file_plugin_key_management_v1_key_management_proto_rawDescGZIP(), []int{12}
}

func (x *GetImportParametersResponse) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *GetImportParametersResponse) GetImportParameters() *structpb.Struct {
	if x != nil {
		return x.ImportParameters
	}
	return nil
}

// ImportKeyMaterialRequest contains parameters for importing key material
type ImportKeyMaterialRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Parameters           *RequestParameters     `protobuf:"bytes,1,opt,name=parameters,proto3" json:"parameters,omitempty"`
	ImportParameters     *structpb.Struct       `protobuf:"bytes,2,opt,name=import_parameters,json=importParameters,proto3" json:"import_parameters,omitempty"`               // The parameters needed for importing key material
	EncryptedKeyMaterial string                 `protobuf:"bytes,3,opt,name=encrypted_key_material,json=encryptedKeyMaterial,proto3" json:"encrypted_key_material,omitempty"` // The encrypted key material to be imported
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ImportKeyMaterialRequest) Reset() {
	*x = ImportKeyMaterialRequest{}
	mi := &file_plugin_key_management_v1_key_management_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportKeyMaterialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportKeyMaterialRequest) ProtoMessage() {}

func (x *ImportKeyMaterialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_key_management_v1_key_management_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportKeyMaterialRequest.ProtoReflect.Descriptor instead.
func (*ImportKeyMaterialRequest) Descriptor() ([]byte, []int) {
	return file_plugin_key_management_v1_key_management_proto_rawDescGZIP(), []int{13}
}

func (x *ImportKeyMaterialRequest) GetParameters() *RequestParameters {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *ImportKeyMaterialRequest) GetImportParameters() *structpb.Struct {
	if x != nil {
		return x.ImportParameters
	}
	return nil
}

func (x *ImportKeyMaterialRequest) GetEncryptedKeyMaterial() string {
	if x != nil {
		return x.EncryptedKeyMaterial
	}
	return ""
}

// ImportKeyMaterialResponse contains the response for key material import
type ImportKeyMaterialResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportKeyMaterialResponse) Reset() {
	*x = ImportKeyMaterialResponse{}
	mi := &file_plugin_key_management_v1_key_management_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportKeyMaterialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportKeyMaterialResponse) ProtoMessage() {}

func (x *ImportKeyMaterialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_key_management_v1_key_management_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportKeyMaterialResponse.ProtoReflect.Descriptor instead.
func (*ImportKeyMaterialResponse) Descriptor() ([]byte, []int) {
	return file_plugin_key_management_v1_key_management_proto_rawDescGZIP(), []int{14}
}

// ValidateKeyRequest contains parameters for validating key attributes
type ValidateKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyType       KeyType                `protobuf:"varint,1,opt,name=key_type,json=keyType,proto3,enum=plugin.key_management.v1.KeyType" json:"key_type,omitempty"`
	Algorithm     Algorithm              `protobuf:"varint,2,opt,name=algorithm,proto3,enum=plugin.key_management.v1.Algorithm" json:"algorithm,omitempty"`
	Region        string                 `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`                                // The region in which the key is to be validated
	NativeKeyId   string                 `protobuf:"bytes,4,opt,name=native_key_id,json=nativeKeyId,proto3" json:"native_key_id,omitempty"` // The native key ID if applicable
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateKeyRequest) Reset() {
	*x = ValidateKeyRequest{}
	mi := &file_plugin_key_management_v1_key_management_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateKeyRequest) ProtoMessage() {}

func (x *ValidateKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_key_management_v1_key_management_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateKeyRequest.ProtoReflect.Descriptor instead.
func (*ValidateKeyRequest) Descriptor() ([]byte, []int) {
	return file_plugin_key_management_v1_key_management_proto_rawDescGZIP(), []int{15}
}

func (x *ValidateKeyRequest) GetKeyType() KeyType {
	if x != nil {
		return x.KeyType
	}
	return KeyType_UNSPECIFIED
}

func (x *ValidateKeyRequest) GetAlgorithm() Algorithm {
	if x != nil {
		return x.Algorithm
	}
	return Algorithm_UNKNOWN
}

func (x *ValidateKeyRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *ValidateKeyRequest) GetNativeKeyId() string {
	if x != nil {
		return x.NativeKeyId
	}
	return ""
}

// ValidateKeyResponse contains the result of key validation
type ValidateKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsValid       bool                   `protobuf:"varint,1,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"` // Indicates if the key attributes are valid
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                 // Additional information about the validation result
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateKeyResponse) Reset() {
	*x = ValidateKeyResponse{}
	mi := &file_plugin_key_management_v1_key_management_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateKeyResponse) ProtoMessage() {}

func (x *ValidateKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_key_management_v1_key_management_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateKeyResponse.ProtoReflect.Descriptor instead.
func (*ValidateKeyResponse) Descriptor() ([]byte, []int) {
	return file_plugin_key_management_v1_key_management_proto_rawDescGZIP(), []int{16}
}

func (x *ValidateKeyResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

func (x *ValidateKeyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ValidateKeyAccessDataRequest contains access data for key management and crypto operations
type ValidateKeyAccessDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Management    *structpb.Struct       `protobuf:"bytes,1,opt,name=management,proto3" json:"management,omitempty"`
	Crypto        *structpb.Struct       `protobuf:"bytes,2,opt,name=crypto,proto3" json:"crypto,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateKeyAccessDataRequest) Reset() {
	*x = ValidateKeyAccessDataRequest{}
	mi := &file_plugin_key_management_v1_key_management_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateKeyAccessDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateKeyAccessDataRequest) ProtoMessage() {}

func (x *ValidateKeyAccessDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_key_management_v1_key_management_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateKeyAccessDataRequest.ProtoReflect.Descriptor instead.
func (*ValidateKeyAccessDataRequest) Descriptor() ([]byte, []int) {
	return file_plugin_key_management_v1_key_management_proto_rawDescGZIP(), []int{17}
}

func (x *ValidateKeyAccessDataRequest) GetManagement() *structpb.Struct {
	if x != nil {
		return x.Management
	}
	return nil
}

func (x *ValidateKeyAccessDataRequest) GetCrypto() *structpb.Struct {
	if x != nil {
		return x.Crypto
	}
	return nil
}

// ValidateKeyAccessDataResponse contains the result of key access data validation
type ValidateKeyAccessDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsValid       bool                   `protobuf:"varint,1,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"` // Indicates if the key access data is valid
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                 // Additional information about the validation result
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateKeyAccessDataResponse) Reset() {
	*x = ValidateKeyAccessDataResponse{}
	mi := &file_plugin_key_management_v1_key_management_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateKeyAccessDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateKeyAccessDataResponse) ProtoMessage() {}

func (x *ValidateKeyAccessDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_key_management_v1_key_management_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateKeyAccessDataResponse.ProtoReflect.Descriptor instead.
func (*ValidateKeyAccessDataResponse) Descriptor() ([]byte, []int) {
	return file_plugin_key_management_v1_key_management_proto_rawDescGZIP(), []int{18}
}

func (x *ValidateKeyAccessDataResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

func (x *ValidateKeyAccessDataResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// TransformCryptoAccessDataRequest contains parameters for transforming crypto access data
type TransformCryptoAccessDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NativeKeyId   string                 `protobuf:"bytes,1,opt,name=native_key_id,json=nativeKeyId,proto3" json:"native_key_id,omitempty"` // The native key ID for which the access data is transformed
	AccessData    []byte                 `protobuf:"bytes,2,opt,name=access_data,json=accessData,proto3" json:"access_data,omitempty"`      // The JSON crypto access data to be transformed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransformCryptoAccessDataRequest) Reset() {
	*x = TransformCryptoAccessDataRequest{}
	mi := &file_plugin_key_management_v1_key_management_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransformCryptoAccessDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransformCryptoAccessDataRequest) ProtoMessage() {}

func (x *TransformCryptoAccessDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_key_management_v1_key_management_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransformCryptoAccessDataRequest.ProtoReflect.Descriptor instead.
func (*TransformCryptoAccessDataRequest) Descriptor() ([]byte, []int) {
	return file_plugin_key_management_v1_key_management_proto_rawDescGZIP(), []int{19}
}

func (x *TransformCryptoAccessDataRequest) GetNativeKeyId() string {
	if x != nil {
		return x.NativeKeyId
	}
	return ""
}

func (x *TransformCryptoAccessDataRequest) GetAccessData() []byte {
	if x != nil {
		return x.AccessData
	}
	return nil
}

// TransformCryptoAccessDataResponse contains the transformed crypto access data
type TransformCryptoAccessDataResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	TransformedAccessData map[string][]byte      `protobuf:"bytes,1,rep,name=transformed_access_data,json=transformedAccessData,proto3" json:"transformed_access_data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // The transformed crypto access data in wire format
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *TransformCryptoAccessDataResponse) Reset() {
	*x = TransformCryptoAccessDataResponse{}
	mi := &file_plugin_key_management_v1_key_management_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransformCryptoAccessDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransformCryptoAccessDataResponse) ProtoMessage() {}

func (x *TransformCryptoAccessDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_key_management_v1_key_management_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransformCryptoAccessDataResponse.ProtoReflect.Descriptor instead.
func (*TransformCryptoAccessDataResponse) Descriptor() ([]byte, []int) {
	return file_plugin_key_management_v1_key_management_proto_rawDescGZIP(), []int{20}
}

func (x *TransformCryptoAccessDataResponse) GetTransformedAccessData() map[string][]byte {
	if x != nil {
		return x.TransformedAccessData
	}
	return nil
}

// ExtractKeyRegionRequest contains parameters for extracting the key region
type ExtractKeyRegionRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	NativeKeyId          string                 `protobuf:"bytes,1,opt,name=native_key_id,json=nativeKeyId,proto3" json:"native_key_id,omitempty"`                            // The region can be derived from the native key ID
	ManagementAccessData *structpb.Struct       `protobuf:"bytes,2,opt,name=management_access_data,json=managementAccessData,proto3" json:"management_access_data,omitempty"` // Or the access details of the management role
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ExtractKeyRegionRequest) Reset() {
	*x = ExtractKeyRegionRequest{}
	mi := &file_plugin_key_management_v1_key_management_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractKeyRegionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractKeyRegionRequest) ProtoMessage() {}

func (x *ExtractKeyRegionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_key_management_v1_key_management_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractKeyRegionRequest.ProtoReflect.Descriptor instead.
func (*ExtractKeyRegionRequest) Descriptor() ([]byte, []int) {
	return file_plugin_key_management_v1_key_management_proto_rawDescGZIP(), []int{21}
}

func (x *ExtractKeyRegionRequest) GetNativeKeyId() string {
	if x != nil {
		return x.NativeKeyId
	}
	return ""
}

func (x *ExtractKeyRegionRequest) GetManagementAccessData() *structpb.Struct {
	if x != nil {
		return x.ManagementAccessData
	}
	return nil
}

// ExtractKeyRegionResponse contains the extracted key region
type ExtractKeyRegionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Region        string                 `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"` // The extracted region from the key attributes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtractKeyRegionResponse) Reset() {
	*x = ExtractKeyRegionResponse{}
	mi := &file_plugin_key_management_v1_key_management_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractKeyRegionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractKeyRegionResponse) ProtoMessage() {}

func (x *ExtractKeyRegionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_key_management_v1_key_management_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractKeyRegionResponse.ProtoReflect.Descriptor instead.
func (*ExtractKeyRegionResponse) Descriptor() ([]byte, []int) {
	return file_plugin_key_management_v1_key_management_proto_rawDescGZIP(), []int{22}
}

func (x *ExtractKeyRegionResponse) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

var File_plugin_key_management_v1_key_management_proto protoreflect.FileDescriptor

const file_plugin_key_management_v1_key_management_proto_rawDesc = "" +
	"\n" +
	"-plugin/key_management/v1/key_management.proto\x12\x18plugin.key_management.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1dplugin/common/v1/common.proto\"l\n" +
	"\x11RequestParameters\x12@\n" +
	"\x06config\x18\x01 \x01(\v2(.plugin.common.v1.KeystoreInstanceConfigR\x06config\x12\x15\n" +
	"\x06key_id\x18\x02 \x01(\tR\x05keyId\"\\\n" +
	"\rGetKeyRequest\x12K\n" +
	"\n" +
	"parameters\x18\x01 \x01(\v2+.plugin.key_management.v1.RequestParametersR\n" +
	"parameters\"\x98\x01\n" +
	"\x0eGetKeyResponse\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12A\n" +
	"\talgorithm\x18\x02 \x01(\x0e2#.plugin.key_management.v1.AlgorithmR\talgorithm\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x14\n" +
	"\x05usage\x18\x04 \x01(\tR\x05usage\"\x89\x02\n" +
	"\x10CreateKeyRequest\x12@\n" +
	"\x06config\x18\x01 \x01(\v2(.plugin.common.v1.KeystoreInstanceConfigR\x06config\x12A\n" +
	"\talgorithm\x18\x02 \x01(\x0e2#.plugin.key_management.v1.AlgorithmR\talgorithm\x12\x13\n" +
	"\x02id\x18\x03 \x01(\tH\x00R\x02id\x88\x01\x01\x12\x16\n" +
	"\x06region\x18\x04 \x01(\tR\x06region\x12<\n" +
	"\bkey_type\x18\x05 \x01(\x0e2!.plugin.key_management.v1.KeyTypeR\akeyTypeB\x05\n" +
	"\x03_id\"B\n" +
	"\x11CreateKeyResponse\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\x87\x01\n" +
	"\x10DeleteKeyRequest\x12K\n" +
	"\n" +
	"parameters\x18\x01 \x01(\v2+.plugin.key_management.v1.RequestParametersR\n" +
	"parameters\x12\x1b\n" +
	"\x06window\x18\x02 \x01(\x05H\x00R\x06window\x88\x01\x01B\t\n" +
	"\a_window\"\x13\n" +
	"\x11DeleteKeyResponse\"_\n" +
	"\x10EnableKeyRequest\x12K\n" +
	"\n" +
	"parameters\x18\x01 \x01(\v2+.plugin.key_management.v1.RequestParametersR\n" +
	"parameters\"\x13\n" +
	"\x11EnableKeyResponse\"`\n" +
	"\x11DisableKeyRequest\x12K\n" +
	"\n" +
	"parameters\x18\x01 \x01(\v2+.plugin.key_management.v1.RequestParametersR\n" +
	"parameters\"\x14\n" +
	"\x12DisableKeyResponse\"\xac\x01\n" +
	"\x1aGetImportParametersRequest\x12K\n" +
	"\n" +
	"parameters\x18\x01 \x01(\v2+.plugin.key_management.v1.RequestParametersR\n" +
	"parameters\x12A\n" +
	"\talgorithm\x18\x02 \x01(\x0e2#.plugin.key_management.v1.AlgorithmR\talgorithm\"z\n" +
	"\x1bGetImportParametersResponse\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12D\n" +
	"\x11import_parameters\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x10importParameters\"\xe3\x01\n" +
	"\x18ImportKeyMaterialRequest\x12K\n" +
	"\n" +
	"parameters\x18\x01 \x01(\v2+.plugin.key_management.v1.RequestParametersR\n" +
	"parameters\x12D\n" +
	"\x11import_parameters\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x10importParameters\x124\n" +
	"\x16encrypted_key_material\x18\x03 \x01(\tR\x14encryptedKeyMaterial\"\x1b\n" +
	"\x19ImportKeyMaterialResponse\"\xd1\x01\n" +
	"\x12ValidateKeyRequest\x12<\n" +
	"\bkey_type\x18\x01 \x01(\x0e2!.plugin.key_management.v1.KeyTypeR\akeyType\x12A\n" +
	"\talgorithm\x18\x02 \x01(\x0e2#.plugin.key_management.v1.AlgorithmR\talgorithm\x12\x16\n" +
	"\x06region\x18\x03 \x01(\tR\x06region\x12\"\n" +
	"\rnative_key_id\x18\x04 \x01(\tR\vnativeKeyId\"J\n" +
	"\x13ValidateKeyResponse\x12\x19\n" +
	"\bis_valid\x18\x01 \x01(\bR\aisValid\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x88\x01\n" +
	"\x1cValidateKeyAccessDataRequest\x127\n" +
	"\n" +
	"management\x18\x01 \x01(\v2\x17.google.protobuf.StructR\n" +
	"management\x12/\n" +
	"\x06crypto\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x06crypto\"T\n" +
	"\x1dValidateKeyAccessDataResponse\x12\x19\n" +
	"\bis_valid\x18\x01 \x01(\bR\aisValid\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"g\n" +
	" TransformCryptoAccessDataRequest\x12\"\n" +
	"\rnative_key_id\x18\x01 \x01(\tR\vnativeKeyId\x12\x1f\n" +
	"\vaccess_data\x18\x02 \x01(\fR\n" +
	"accessData\"\xfe\x01\n" +
	"!TransformCryptoAccessDataResponse\x12\x8e\x01\n" +
	"\x17transformed_access_data\x18\x01 \x03(\v2V.plugin.key_management.v1.TransformCryptoAccessDataResponse.TransformedAccessDataEntryR\x15transformedAccessData\x1aH\n" +
	"\x1aTransformedAccessDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"\x8c\x01\n" +
	"\x17ExtractKeyRegionRequest\x12\"\n" +
	"\rnative_key_id\x18\x01 \x01(\tR\vnativeKeyId\x12M\n" +
	"\x16management_access_data\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x14managementAccessData\"2\n" +
	"\x18ExtractKeyRegionResponse\x12\x16\n" +
	"\x06region\x18\x01 \x01(\tR\x06region*>\n" +
	"\tAlgorithm\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\n" +
	"\n" +
	"\x06AES256\x10\x01\x12\v\n" +
	"\aRSA3072\x10\x02\x12\v\n" +
	"\aRSA4096\x10\x03*B\n" +
	"\aKeyType\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSYSTEM_MANAGED\x10\x01\x12\b\n" +
	"\x04BYOK\x10\x02\x12\b\n" +
	"\x04HYOK\x10\x032\x93\n" +
	"\n" +
	"\rKeyManagement\x12[\n" +
	"\x06GetKey\x12'.plugin.key_management.v1.GetKeyRequest\x1a(.plugin.key_management.v1.GetKeyResponse\x12d\n" +
	"\tCreateKey\x12*.plugin.key_management.v1.CreateKeyRequest\x1a+.plugin.key_management.v1.CreateKeyResponse\x12d\n" +
	"\tDeleteKey\x12*.plugin.key_management.v1.DeleteKeyRequest\x1a+.plugin.key_management.v1.DeleteKeyResponse\x12d\n" +
	"\tEnableKey\x12*.plugin.key_management.v1.EnableKeyRequest\x1a+.plugin.key_management.v1.EnableKeyResponse\x12g\n" +
	"\n" +
	"DisableKey\x12+.plugin.key_management.v1.DisableKeyRequest\x1a,.plugin.key_management.v1.DisableKeyResponse\x12\x82\x01\n" +
	"\x13GetImportParameters\x124.plugin.key_management.v1.GetImportParametersRequest\x1a5.plugin.key_management.v1.GetImportParametersResponse\x12|\n" +
	"\x11ImportKeyMaterial\x122.plugin.key_management.v1.ImportKeyMaterialRequest\x1a3.plugin.key_management.v1.ImportKeyMaterialResponse\x12j\n" +
	"\vValidateKey\x12,.plugin.key_management.v1.ValidateKeyRequest\x1a-.plugin.key_management.v1.ValidateKeyResponse\x12\x88\x01\n" +
	"\x15ValidateKeyAccessData\x126.plugin.key_management.v1.ValidateKeyAccessDataRequest\x1a7.plugin.key_management.v1.ValidateKeyAccessDataResponse\x12\x94\x01\n" +
	"\x19TransformCryptoAccessData\x12:.plugin.key_management.v1.TransformCryptoAccessDataRequest\x1a;.plugin.key_management.v1.TransformCryptoAccessDataResponse\x12y\n" +
	"\x10ExtractKeyRegion\x121.plugin.key_management.v1.ExtractKeyRegionRequest\x1a2.plugin.key_management.v1.ExtractKeyRegionResponseB\xff\x01\n" +
	"\x1ccom.plugin.key_management.v1B\x12KeyManagementProtoP\x01ZMgithub.com/openkcm/plugin-sdk/proto/plugin/key_management/v1;key_managementv1\xa2\x02\x03PKX\xaa\x02\x17Plugin.KeyManagement.V1\xca\x02\x17Plugin\\KeyManagement\\V1\xe2\x02#Plugin\\KeyManagement\\V1\\GPBMetadata\xea\x02\x19Plugin::KeyManagement::V1b\x06proto3"

var (
	file_plugin_key_management_v1_key_management_proto_rawDescOnce sync.Once
	file_plugin_key_management_v1_key_management_proto_rawDescData []byte
)

func file_plugin_key_management_v1_key_management_proto_rawDescGZIP() []byte {
	file_plugin_key_management_v1_key_management_proto_rawDescOnce.Do(func() {
		file_plugin_key_management_v1_key_management_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_key_management_v1_key_management_proto_rawDesc), len(file_plugin_key_management_v1_key_management_proto_rawDesc)))
	})
	return file_plugin_key_management_v1_key_management_proto_rawDescData
}

var file_plugin_key_management_v1_key_management_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_plugin_key_management_v1_key_management_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_plugin_key_management_v1_key_management_proto_goTypes = []any{
	(Algorithm)(0),                            // 0: plugin.key_management.v1.Algorithm
	(KeyType)(0),                              // 1: plugin.key_management.v1.KeyType
	(*RequestParameters)(nil),                 // 2: plugin.key_management.v1.RequestParameters
	(*GetKeyRequest)(nil),                     // 3: plugin.key_management.v1.GetKeyRequest
	(*GetKeyResponse)(nil),                    // 4: plugin.key_management.v1.GetKeyResponse
	(*CreateKeyRequest)(nil),                  // 5: plugin.key_management.v1.CreateKeyRequest
	(*CreateKeyResponse)(nil),                 // 6: plugin.key_management.v1.CreateKeyResponse
	(*DeleteKeyRequest)(nil),                  // 7: plugin.key_management.v1.DeleteKeyRequest
	(*DeleteKeyResponse)(nil),                 // 8: plugin.key_management.v1.DeleteKeyResponse
	(*EnableKeyRequest)(nil),                  // 9: plugin.key_management.v1.EnableKeyRequest
	(*EnableKeyResponse)(nil),                 // 10: plugin.key_management.v1.EnableKeyResponse
	(*DisableKeyRequest)(nil),                 // 11: plugin.key_management.v1.DisableKeyRequest
	(*DisableKeyResponse)(nil),                // 12: plugin.key_management.v1.DisableKeyResponse
	(*GetImportParametersRequest)(nil),        // 13: plugin.key_management.v1.GetImportParametersRequest
	(*GetImportParametersResponse)(nil),       // 14: plugin.key_management.v1.GetImportParametersResponse
	(*ImportKeyMaterialRequest)(nil),          // 15: plugin.key_management.v1.ImportKeyMaterialRequest
	(*ImportKeyMaterialResponse)(nil),         // 16: plugin.key_management.v1.ImportKeyMaterialResponse
	(*ValidateKeyRequest)(nil),                // 17: plugin.key_management.v1.ValidateKeyRequest
	(*ValidateKeyResponse)(nil),               // 18: plugin.key_management.v1.ValidateKeyResponse
	(*ValidateKeyAccessDataRequest)(nil),      // 19: plugin.key_management.v1.ValidateKeyAccessDataRequest
	(*ValidateKeyAccessDataResponse)(nil),     // 20: plugin.key_management.v1.ValidateKeyAccessDataResponse
	(*TransformCryptoAccessDataRequest)(nil),  // 21: plugin.key_management.v1.TransformCryptoAccessDataRequest
	(*TransformCryptoAccessDataResponse)(nil), // 22: plugin.key_management.v1.TransformCryptoAccessDataResponse
	(*ExtractKeyRegionRequest)(nil),           // 23: plugin.key_management.v1.ExtractKeyRegionRequest
	(*ExtractKeyRegionResponse)(nil),          // 24: plugin.key_management.v1.ExtractKeyRegionResponse
	nil,                                       // 25: plugin.key_management.v1.TransformCryptoAccessDataResponse.TransformedAccessDataEntry
	(*v1.KeystoreInstanceConfig)(nil),         // 26: plugin.common.v1.KeystoreInstanceConfig
	(*structpb.Struct)(nil),                   // 27: google.protobuf.Struct
}
var file_plugin_key_management_v1_key_management_proto_depIdxs = []int32{
	26, // 0: plugin.key_management.v1.RequestParameters.config:type_name -> plugin.common.v1.KeystoreInstanceConfig
	2,  // 1: plugin.key_management.v1.GetKeyRequest.parameters:type_name -> plugin.key_management.v1.RequestParameters
	0,  // 2: plugin.key_management.v1.GetKeyResponse.algorithm:type_name -> plugin.key_management.v1.Algorithm
	26, // 3: plugin.key_management.v1.CreateKeyRequest.config:type_name -> plugin.common.v1.KeystoreInstanceConfig
	0,  // 4: plugin.key_management.v1.CreateKeyRequest.algorithm:type_name -> plugin.key_management.v1.Algorithm
	1,  // 5: plugin.key_management.v1.CreateKeyRequest.key_type:type_name -> plugin.key_management.v1.KeyType
	2,  // 6: plugin.key_management.v1.DeleteKeyRequest.parameters:type_name -> plugin.key_management.v1.RequestParameters
	2,  // 7: plugin.key_management.v1.EnableKeyRequest.parameters:type_name -> plugin.key_management.v1.RequestParameters
	2,  // 8: plugin.key_management.v1.DisableKeyRequest.parameters:type_name -> plugin.key_management.v1.RequestParameters
	2,  // 9: plugin.key_management.v1.GetImportParametersRequest.parameters:type_name -> plugin.key_management.v1.RequestParameters
	0,  // 10: plugin.key_management.v1.GetImportParametersRequest.algorithm:type_name -> plugin.key_management.v1.Algorithm
	27, // 11: plugin.key_management.v1.GetImportParametersResponse.import_parameters:type_name -> google.protobuf.Struct
	2,  // 12: plugin.key_management.v1.ImportKeyMaterialRequest.parameters:type_name -> plugin.key_management.v1.RequestParameters
	27, // 13: plugin.key_management.v1.ImportKeyMaterialRequest.import_parameters:type_name -> google.protobuf.Struct
	1,  // 14: plugin.key_management.v1.ValidateKeyRequest.key_type:type_name -> plugin.key_management.v1.KeyType
	0,  // 15: plugin.key_management.v1.ValidateKeyRequest.algorithm:type_name -> plugin.key_management.v1.Algorithm
	27, // 16: plugin.key_management.v1.ValidateKeyAccessDataRequest.management:type_name -> google.protobuf.Struct
	27, // 17: plugin.key_management.v1.ValidateKeyAccessDataRequest.crypto:type_name -> google.protobuf.Struct
	25, // 18: plugin.key_management.v1.TransformCryptoAccessDataResponse.transformed_access_data:type_name -> plugin.key_management.v1.TransformCryptoAccessDataResponse.TransformedAccessDataEntry
	27, // 19: plugin.key_management.v1.ExtractKeyRegionRequest.management_access_data:type_name -> google.protobuf.Struct
	3,  // 20: plugin.key_management.v1.KeyManagement.GetKey:input_type -> plugin.key_management.v1.GetKeyRequest
	5,  // 21: plugin.key_management.v1.KeyManagement.CreateKey:input_type -> plugin.key_management.v1.CreateKeyRequest
	7,  // 22: plugin.key_management.v1.KeyManagement.DeleteKey:input_type -> plugin.key_management.v1.DeleteKeyRequest
	9,  // 23: plugin.key_management.v1.KeyManagement.EnableKey:input_type -> plugin.key_management.v1.EnableKeyRequest
	11, // 24: plugin.key_management.v1.KeyManagement.DisableKey:input_type -> plugin.key_management.v1.DisableKeyRequest
	13, // 25: plugin.key_management.v1.KeyManagement.GetImportParameters:input_type -> plugin.key_management.v1.GetImportParametersRequest
	15, // 26: plugin.key_management.v1.KeyManagement.ImportKeyMaterial:input_type -> plugin.key_management.v1.ImportKeyMaterialRequest
	17, // 27: plugin.key_management.v1.KeyManagement.ValidateKey:input_type -> plugin.key_management.v1.ValidateKeyRequest
	19, // 28: plugin.key_management.v1.KeyManagement.ValidateKeyAccessData:input_type -> plugin.key_management.v1.ValidateKeyAccessDataRequest
	21, // 29: plugin.key_management.v1.KeyManagement.TransformCryptoAccessData:input_type -> plugin.key_management.v1.TransformCryptoAccessDataRequest
	23, // 30: plugin.key_management.v1.KeyManagement.ExtractKeyRegion:input_type -> plugin.key_management.v1.ExtractKeyRegionRequest
	4,  // 31: plugin.key_management.v1.KeyManagement.GetKey:output_type -> plugin.key_management.v1.GetKeyResponse
	6,  // 32: plugin.key_management.v1.KeyManagement.CreateKey:output_type -> plugin.key_management.v1.CreateKeyResponse
	8,  // 33: plugin.key_management.v1.KeyManagement.DeleteKey:output_type -> plugin.key_management.v1.DeleteKeyResponse
	10, // 34: plugin.key_management.v1.KeyManagement.EnableKey:output_type -> plugin.key_management.v1.EnableKeyResponse
	12, // 35: plugin.key_management.v1.KeyManagement.DisableKey:output_type -> plugin.key_management.v1.DisableKeyResponse
	14, // 36: plugin.key_management.v1.KeyManagement.GetImportParameters:output_type -> plugin.key_management.v1.GetImportParametersResponse
	16, // 37: plugin.key_management.v1.KeyManagement.ImportKeyMaterial:output_type -> plugin.key_management.v1.ImportKeyMaterialResponse
	18, // 38: plugin.key_management.v1.KeyManagement.ValidateKey:output_type -> plugin.key_management.v1.ValidateKeyResponse
	20, // 39: plugin.key_management.v1.KeyManagement.ValidateKeyAccessData:output_type -> plugin.key_management.v1.ValidateKeyAccessDataResponse
	22, // 40: plugin.key_management.v1.KeyManagement.TransformCryptoAccessData:output_type -> plugin.key_management.v1.TransformCryptoAccessDataResponse
	24, // 41: plugin.key_management.v1.KeyManagement.ExtractKeyRegion:output_type -> plugin.key_management.v1.ExtractKeyRegionResponse
	31, // [31:42] is the sub-list for method output_type
	20, // [20:31] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_plugin_key_management_v1_key_management_proto_init() }
func file_plugin_key_management_v1_key_management_proto_init() {
	if File_plugin_key_management_v1_key_management_proto != nil {
		return
	}
	file_plugin_key_management_v1_key_management_proto_msgTypes[3].OneofWrappers = []any{}
	file_plugin_key_management_v1_key_management_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_key_management_v1_key_management_proto_rawDesc), len(file_plugin_key_management_v1_key_management_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugin_key_management_v1_key_management_proto_goTypes,
		DependencyIndexes: file_plugin_key_management_v1_key_management_proto_depIdxs,
		EnumInfos:         file_plugin_key_management_v1_key_management_proto_enumTypes,
		MessageInfos:      file_plugin_key_management_v1_key_management_proto_msgTypes,
	}.Build()
	File_plugin_key_management_v1_key_management_proto = out.File
	file_plugin_key_management_v1_key_management_proto_goTypes = nil
	file_plugin_key_management_v1_key_management_proto_depIdxs = nil
}
