// Code generated by protoc-gen-go-extension. DO NOT EDIT.

package llmv1

import (
	grpc "google.golang.org/grpc"

	api "github.com/openkcm/plugin-sdk/api"
)

const (
	Type                = "LLM"
	GRPCServiceFullName = "krypton.llm.v1.LLM"
)

func LLMPluginServer(server LLMServer) api.PluginServer {
	return lLMPluginServer{LLMServer: server}
}

type lLMPluginServer struct {
	LLMServer
}

func (s lLMPluginServer) Type() string {
	return Type
}

func (s lLMPluginServer) GRPCServiceName() string {
	return GRPCServiceFullName
}

func (s lLMPluginServer) RegisterServer(server *grpc.Server) any {
	RegisterLLMServer(server, s.LLMServer)
	return s.LLMServer
}

type LLMPluginClient struct {
	LLMClient
}

func (s LLMPluginClient) Type() string {
	return Type
}

func (c *LLMPluginClient) IsInitialized() bool {
	return c.LLMClient != nil
}

func (c *LLMPluginClient) GRPCServiceName() string {
	return GRPCServiceFullName
}

func (c *LLMPluginClient) InitClient(conn grpc.ClientConnInterface) any {
	c.LLMClient = NewLLMClient(conn)
	return c.LLMClient
}
