version: 3

includes:
  shared:
    taskfile: hack/common/Taskfile_library.yaml
    flatten: true
    excludes: # put task names in here which are overwritten in this file
      - validate:format-imports
    vars:
      CODE_DIRS: '{{.ROOT_DIR}}/pkg/... {{.ROOT_DIR}}/internal/... {{.ROOT_DIR}}/api/...'
      GENERATE_DOCS_INDEX: "false"
