// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: plugin/certificate_issuer/v1/certificate_issuer.proto

package certificate_issuerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	CertificateIssuer_IssueCertificate_FullMethodName = "/plugin.certificate_issuer.v1.CertificateIssuer/IssueCertificate"
)

// CertificateIssuerClient is the client API for CertificateIssuer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CertificateIssuerClient interface {
	IssueCertificate(ctx context.Context, in *IssueCertificateRequest, opts ...grpc.CallOption) (*IssueCertificateResponse, error)
}

type certificateIssuerClient struct {
	cc grpc.ClientConnInterface
}

func NewCertificateIssuerClient(cc grpc.ClientConnInterface) CertificateIssuerClient {
	return &certificateIssuerClient{cc}
}

func (c *certificateIssuerClient) IssueCertificate(ctx context.Context, in *IssueCertificateRequest, opts ...grpc.CallOption) (*IssueCertificateResponse, error) {
	out := new(IssueCertificateResponse)
	err := c.cc.Invoke(ctx, CertificateIssuer_IssueCertificate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CertificateIssuerServer is the server API for CertificateIssuer service.
// All implementations must embed UnimplementedCertificateIssuerServer
// for forward compatibility
type CertificateIssuerServer interface {
	IssueCertificate(context.Context, *IssueCertificateRequest) (*IssueCertificateResponse, error)
	mustEmbedUnimplementedCertificateIssuerServer()
}

// UnimplementedCertificateIssuerServer must be embedded to have forward compatible implementations.
type UnimplementedCertificateIssuerServer struct {
}

func (UnimplementedCertificateIssuerServer) IssueCertificate(context.Context, *IssueCertificateRequest) (*IssueCertificateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IssueCertificate not implemented")
}
func (UnimplementedCertificateIssuerServer) mustEmbedUnimplementedCertificateIssuerServer() {}

// UnsafeCertificateIssuerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CertificateIssuerServer will
// result in compilation errors.
type UnsafeCertificateIssuerServer interface {
	mustEmbedUnimplementedCertificateIssuerServer()
}

func RegisterCertificateIssuerServer(s grpc.ServiceRegistrar, srv CertificateIssuerServer) {
	s.RegisterService(&CertificateIssuer_ServiceDesc, srv)
}

func _CertificateIssuer_IssueCertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IssueCertificateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CertificateIssuerServer).IssueCertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CertificateIssuer_IssueCertificate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CertificateIssuerServer).IssueCertificate(ctx, req.(*IssueCertificateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CertificateIssuer_ServiceDesc is the grpc.ServiceDesc for CertificateIssuer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CertificateIssuer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "plugin.certificate_issuer.v1.CertificateIssuer",
	HandlerType: (*CertificateIssuerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IssueCertificate",
			Handler:    _CertificateIssuer_IssueCertificate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin/certificate_issuer/v1/certificate_issuer.proto",
}
