// Code generated by protoc-gen-go-extension. DO NOT EDIT.

package configv1

import (
	api "github.com/openkcm/plugin-sdk/api"
	grpc "google.golang.org/grpc"
)

const (
	GRPCServiceFullName = "service.common.config.v1.Config"
)

func ConfigServiceServer(server ConfigServer) api.ServiceServer {
	return configServiceServer{ConfigServer: server}
}

type configServiceServer struct {
	ConfigServer
}

func (s configServiceServer) GRPCServiceName() string {
	return GRPCServiceFullName
}

func (s configServiceServer) RegisterServer(server *grpc.Server) any {
	RegisterConfigServer(server, s.ConfigServer)
	return s.ConfigServer
}

type ConfigServiceClient struct {
	ConfigClient
}

func (c *ConfigServiceClient) IsInitialized() bool {
	return c.ConfigClient != nil
}

func (c *ConfigServiceClient) GRPCServiceName() string {
	return GRPCServiceFullName
}

func (c *ConfigServiceClient) InitClient(conn grpc.ClientConnInterface) any {
	c.ConfigClient = NewConfigClient(conn)
	return c.ConfigClient
}
