// Code generated by protoc-gen-go-extension. DO NOT EDIT.

package identity_managementv1

import (
	api "github.com/openkcm/plugin-sdk/api"
	grpc "google.golang.org/grpc"
)

const (
	Type                = "IdentityManagementService"
	GRPCServiceFullName = "plugin.identity_management.v1.IdentityManagementService"
)

func IdentityManagementServicePluginServer(server IdentityManagementServiceServer) api.PluginServer {
	return identityManagementServicePluginServer{IdentityManagementServiceServer: server}
}

type identityManagementServicePluginServer struct {
	IdentityManagementServiceServer
}

func (s identityManagementServicePluginServer) Type() string {
	return Type
}

func (s identityManagementServicePluginServer) GRPCServiceName() string {
	return GRPCServiceFullName
}

func (s identityManagementServicePluginServer) RegisterServer(server *grpc.Server) any {
	RegisterIdentityManagementServiceServer(server, s.IdentityManagementServiceServer)
	return s.IdentityManagementServiceServer
}

type IdentityManagementServicePluginClient struct {
	IdentityManagementServiceClient
}

func (s IdentityManagementServicePluginClient) Type() string {
	return Type
}

func (c *IdentityManagementServicePluginClient) IsInitialized() bool {
	return c.IdentityManagementServiceClient != nil
}

func (c *IdentityManagementServicePluginClient) GRPCServiceName() string {
	return GRPCServiceFullName
}

func (c *IdentityManagementServicePluginClient) InitClient(conn grpc.ClientConnInterface) any {
	c.IdentityManagementServiceClient = NewIdentityManagementServiceClient(conn)
	return c.IdentityManagementServiceClient
}
