// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: plugin/identity_management/v1/identity_management.proto

package identity_managementv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          map[string]string      `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthContext) Reset() {
	*x = AuthContext{}
	mi := &file_plugin_identity_management_v1_identity_management_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthContext) ProtoMessage() {}

func (x *AuthContext) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_identity_management_v1_identity_management_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthContext.ProtoReflect.Descriptor instead.
func (*AuthContext) Descriptor() ([]byte, []int) {
	return file_plugin_identity_management_v1_identity_management_proto_rawDescGZIP(), []int{0}
}

func (x *AuthContext) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupName     string                 `protobuf:"bytes,1,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	AuthContext   *AuthContext           `protobuf:"bytes,99,opt,name=auth_context,json=authContext,proto3" json:"auth_context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupRequest) Reset() {
	*x = GetGroupRequest{}
	mi := &file_plugin_identity_management_v1_identity_management_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupRequest) ProtoMessage() {}

func (x *GetGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_identity_management_v1_identity_management_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupRequest.ProtoReflect.Descriptor instead.
func (*GetGroupRequest) Descriptor() ([]byte, []int) {
	return file_plugin_identity_management_v1_identity_management_proto_rawDescGZIP(), []int{1}
}

func (x *GetGroupRequest) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *GetGroupRequest) GetAuthContext() *AuthContext {
	if x != nil {
		return x.AuthContext
	}
	return nil
}

type GetGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         *Group                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupResponse) Reset() {
	*x = GetGroupResponse{}
	mi := &file_plugin_identity_management_v1_identity_management_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupResponse) ProtoMessage() {}

func (x *GetGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_identity_management_v1_identity_management_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupResponse.ProtoReflect.Descriptor instead.
func (*GetGroupResponse) Descriptor() ([]byte, []int) {
	return file_plugin_identity_management_v1_identity_management_proto_rawDescGZIP(), []int{2}
}

func (x *GetGroupResponse) GetGroup() *Group {
	if x != nil {
		return x.Group
	}
	return nil
}

type GetAllGroupsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthContext   *AuthContext           `protobuf:"bytes,99,opt,name=auth_context,json=authContext,proto3" json:"auth_context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllGroupsRequest) Reset() {
	*x = GetAllGroupsRequest{}
	mi := &file_plugin_identity_management_v1_identity_management_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllGroupsRequest) ProtoMessage() {}

func (x *GetAllGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_identity_management_v1_identity_management_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllGroupsRequest.ProtoReflect.Descriptor instead.
func (*GetAllGroupsRequest) Descriptor() ([]byte, []int) {
	return file_plugin_identity_management_v1_identity_management_proto_rawDescGZIP(), []int{3}
}

func (x *GetAllGroupsRequest) GetAuthContext() *AuthContext {
	if x != nil {
		return x.AuthContext
	}
	return nil
}

type GetAllGroupsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Groups        []*Group               `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllGroupsResponse) Reset() {
	*x = GetAllGroupsResponse{}
	mi := &file_plugin_identity_management_v1_identity_management_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllGroupsResponse) ProtoMessage() {}

func (x *GetAllGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_identity_management_v1_identity_management_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllGroupsResponse.ProtoReflect.Descriptor instead.
func (*GetAllGroupsResponse) Descriptor() ([]byte, []int) {
	return file_plugin_identity_management_v1_identity_management_proto_rawDescGZIP(), []int{4}
}

func (x *GetAllGroupsResponse) GetGroups() []*Group {
	if x != nil {
		return x.Groups
	}
	return nil
}

type GetUsersForGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	AuthContext   *AuthContext           `protobuf:"bytes,99,opt,name=auth_context,json=authContext,proto3" json:"auth_context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersForGroupRequest) Reset() {
	*x = GetUsersForGroupRequest{}
	mi := &file_plugin_identity_management_v1_identity_management_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersForGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersForGroupRequest) ProtoMessage() {}

func (x *GetUsersForGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_identity_management_v1_identity_management_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersForGroupRequest.ProtoReflect.Descriptor instead.
func (*GetUsersForGroupRequest) Descriptor() ([]byte, []int) {
	return file_plugin_identity_management_v1_identity_management_proto_rawDescGZIP(), []int{5}
}

func (x *GetUsersForGroupRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *GetUsersForGroupRequest) GetAuthContext() *AuthContext {
	if x != nil {
		return x.AuthContext
	}
	return nil
}

type GetUsersForGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersForGroupResponse) Reset() {
	*x = GetUsersForGroupResponse{}
	mi := &file_plugin_identity_management_v1_identity_management_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersForGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersForGroupResponse) ProtoMessage() {}

func (x *GetUsersForGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_identity_management_v1_identity_management_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersForGroupResponse.ProtoReflect.Descriptor instead.
func (*GetUsersForGroupResponse) Descriptor() ([]byte, []int) {
	return file_plugin_identity_management_v1_identity_management_proto_rawDescGZIP(), []int{6}
}

func (x *GetUsersForGroupResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_plugin_identity_management_v1_identity_management_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_identity_management_v1_identity_management_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_plugin_identity_management_v1_identity_management_proto_rawDescGZIP(), []int{7}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type GetGroupsForUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AuthContext   *AuthContext           `protobuf:"bytes,99,opt,name=auth_context,json=authContext,proto3" json:"auth_context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupsForUserRequest) Reset() {
	*x = GetGroupsForUserRequest{}
	mi := &file_plugin_identity_management_v1_identity_management_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupsForUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupsForUserRequest) ProtoMessage() {}

func (x *GetGroupsForUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_identity_management_v1_identity_management_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupsForUserRequest.ProtoReflect.Descriptor instead.
func (*GetGroupsForUserRequest) Descriptor() ([]byte, []int) {
	return file_plugin_identity_management_v1_identity_management_proto_rawDescGZIP(), []int{8}
}

func (x *GetGroupsForUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetGroupsForUserRequest) GetAuthContext() *AuthContext {
	if x != nil {
		return x.AuthContext
	}
	return nil
}

type GetGroupsForUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Groups        []*Group               `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupsForUserResponse) Reset() {
	*x = GetGroupsForUserResponse{}
	mi := &file_plugin_identity_management_v1_identity_management_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupsForUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupsForUserResponse) ProtoMessage() {}

func (x *GetGroupsForUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_identity_management_v1_identity_management_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupsForUserResponse.ProtoReflect.Descriptor instead.
func (*GetGroupsForUserResponse) Descriptor() ([]byte, []int) {
	return file_plugin_identity_management_v1_identity_management_proto_rawDescGZIP(), []int{9}
}

func (x *GetGroupsForUserResponse) GetGroups() []*Group {
	if x != nil {
		return x.Groups
	}
	return nil
}

type Group struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Group) Reset() {
	*x = Group{}
	mi := &file_plugin_identity_management_v1_identity_management_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Group) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Group) ProtoMessage() {}

func (x *Group) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_identity_management_v1_identity_management_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Group.ProtoReflect.Descriptor instead.
func (*Group) Descriptor() ([]byte, []int) {
	return file_plugin_identity_management_v1_identity_management_proto_rawDescGZIP(), []int{10}
}

func (x *Group) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Group) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_plugin_identity_management_v1_identity_management_proto protoreflect.FileDescriptor

const file_plugin_identity_management_v1_identity_management_proto_rawDesc = "" +
	"\n" +
	"7plugin/identity_management/v1/identity_management.proto\x12\x1dplugin.identity_management.v1\"\x90\x01\n" +
	"\vAuthContext\x12H\n" +
	"\x04data\x18\x01 \x03(\v24.plugin.identity_management.v1.AuthContext.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x7f\n" +
	"\x0fGetGroupRequest\x12\x1d\n" +
	"\n" +
	"group_name\x18\x01 \x01(\tR\tgroupName\x12M\n" +
	"\fauth_context\x18c \x01(\v2*.plugin.identity_management.v1.AuthContextR\vauthContext\"N\n" +
	"\x10GetGroupResponse\x12:\n" +
	"\x05group\x18\x01 \x01(\v2$.plugin.identity_management.v1.GroupR\x05group\"d\n" +
	"\x13GetAllGroupsRequest\x12M\n" +
	"\fauth_context\x18c \x01(\v2*.plugin.identity_management.v1.AuthContextR\vauthContext\"T\n" +
	"\x14GetAllGroupsResponse\x12<\n" +
	"\x06groups\x18\x01 \x03(\v2$.plugin.identity_management.v1.GroupR\x06groups\"\x83\x01\n" +
	"\x17GetUsersForGroupRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12M\n" +
	"\fauth_context\x18c \x01(\v2*.plugin.identity_management.v1.AuthContextR\vauthContext\"U\n" +
	"\x18GetUsersForGroupResponse\x129\n" +
	"\x05users\x18\x01 \x03(\v2#.plugin.identity_management.v1.UserR\x05users\"@\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\"\x81\x01\n" +
	"\x17GetGroupsForUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12M\n" +
	"\fauth_context\x18c \x01(\v2*.plugin.identity_management.v1.AuthContextR\vauthContext\"X\n" +
	"\x18GetGroupsForUserResponse\x12<\n" +
	"\x06groups\x18\x01 \x03(\v2$.plugin.identity_management.v1.GroupR\x06groups\"+\n" +
	"\x05Group\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name2\x8d\x04\n" +
	"\x19IdentityManagementService\x12k\n" +
	"\bGetGroup\x12..plugin.identity_management.v1.GetGroupRequest\x1a/.plugin.identity_management.v1.GetGroupResponse\x12w\n" +
	"\fGetAllGroups\x122.plugin.identity_management.v1.GetAllGroupsRequest\x1a3.plugin.identity_management.v1.GetAllGroupsResponse\x12\x83\x01\n" +
	"\x10GetUsersForGroup\x126.plugin.identity_management.v1.GetUsersForGroupRequest\x1a7.plugin.identity_management.v1.GetUsersForGroupResponse\x12\x83\x01\n" +
	"\x10GetGroupsForUser\x126.plugin.identity_management.v1.GetGroupsForUserRequest\x1a7.plugin.identity_management.v1.GetGroupsForUserResponseB\xa7\x02\n" +
	"!com.plugin.identity_management.v1B\x17IdentityManagementProtoP\x01ZWgithub.com/openkcm/plugin-sdk/proto/plugin/identity_management/v1;identity_managementv1\xa2\x02\x03PIX\xaa\x02\x1cPlugin.IdentityManagement.V1\xca\x02\x1cPlugin\\IdentityManagement\\V1\xe2\x02(Plugin\\IdentityManagement\\V1\\GPBMetadata\xea\x02\x1ePlugin::IdentityManagement::V1b\x06proto3"

var (
	file_plugin_identity_management_v1_identity_management_proto_rawDescOnce sync.Once
	file_plugin_identity_management_v1_identity_management_proto_rawDescData []byte
)

func file_plugin_identity_management_v1_identity_management_proto_rawDescGZIP() []byte {
	file_plugin_identity_management_v1_identity_management_proto_rawDescOnce.Do(func() {
		file_plugin_identity_management_v1_identity_management_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_identity_management_v1_identity_management_proto_rawDesc), len(file_plugin_identity_management_v1_identity_management_proto_rawDesc)))
	})
	return file_plugin_identity_management_v1_identity_management_proto_rawDescData
}

var file_plugin_identity_management_v1_identity_management_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_plugin_identity_management_v1_identity_management_proto_goTypes = []any{
	(*AuthContext)(nil),              // 0: plugin.identity_management.v1.AuthContext
	(*GetGroupRequest)(nil),          // 1: plugin.identity_management.v1.GetGroupRequest
	(*GetGroupResponse)(nil),         // 2: plugin.identity_management.v1.GetGroupResponse
	(*GetAllGroupsRequest)(nil),      // 3: plugin.identity_management.v1.GetAllGroupsRequest
	(*GetAllGroupsResponse)(nil),     // 4: plugin.identity_management.v1.GetAllGroupsResponse
	(*GetUsersForGroupRequest)(nil),  // 5: plugin.identity_management.v1.GetUsersForGroupRequest
	(*GetUsersForGroupResponse)(nil), // 6: plugin.identity_management.v1.GetUsersForGroupResponse
	(*User)(nil),                     // 7: plugin.identity_management.v1.User
	(*GetGroupsForUserRequest)(nil),  // 8: plugin.identity_management.v1.GetGroupsForUserRequest
	(*GetGroupsForUserResponse)(nil), // 9: plugin.identity_management.v1.GetGroupsForUserResponse
	(*Group)(nil),                    // 10: plugin.identity_management.v1.Group
	nil,                              // 11: plugin.identity_management.v1.AuthContext.DataEntry
}
var file_plugin_identity_management_v1_identity_management_proto_depIdxs = []int32{
	11, // 0: plugin.identity_management.v1.AuthContext.data:type_name -> plugin.identity_management.v1.AuthContext.DataEntry
	0,  // 1: plugin.identity_management.v1.GetGroupRequest.auth_context:type_name -> plugin.identity_management.v1.AuthContext
	10, // 2: plugin.identity_management.v1.GetGroupResponse.group:type_name -> plugin.identity_management.v1.Group
	0,  // 3: plugin.identity_management.v1.GetAllGroupsRequest.auth_context:type_name -> plugin.identity_management.v1.AuthContext
	10, // 4: plugin.identity_management.v1.GetAllGroupsResponse.groups:type_name -> plugin.identity_management.v1.Group
	0,  // 5: plugin.identity_management.v1.GetUsersForGroupRequest.auth_context:type_name -> plugin.identity_management.v1.AuthContext
	7,  // 6: plugin.identity_management.v1.GetUsersForGroupResponse.users:type_name -> plugin.identity_management.v1.User
	0,  // 7: plugin.identity_management.v1.GetGroupsForUserRequest.auth_context:type_name -> plugin.identity_management.v1.AuthContext
	10, // 8: plugin.identity_management.v1.GetGroupsForUserResponse.groups:type_name -> plugin.identity_management.v1.Group
	1,  // 9: plugin.identity_management.v1.IdentityManagementService.GetGroup:input_type -> plugin.identity_management.v1.GetGroupRequest
	3,  // 10: plugin.identity_management.v1.IdentityManagementService.GetAllGroups:input_type -> plugin.identity_management.v1.GetAllGroupsRequest
	5,  // 11: plugin.identity_management.v1.IdentityManagementService.GetUsersForGroup:input_type -> plugin.identity_management.v1.GetUsersForGroupRequest
	8,  // 12: plugin.identity_management.v1.IdentityManagementService.GetGroupsForUser:input_type -> plugin.identity_management.v1.GetGroupsForUserRequest
	2,  // 13: plugin.identity_management.v1.IdentityManagementService.GetGroup:output_type -> plugin.identity_management.v1.GetGroupResponse
	4,  // 14: plugin.identity_management.v1.IdentityManagementService.GetAllGroups:output_type -> plugin.identity_management.v1.GetAllGroupsResponse
	6,  // 15: plugin.identity_management.v1.IdentityManagementService.GetUsersForGroup:output_type -> plugin.identity_management.v1.GetUsersForGroupResponse
	9,  // 16: plugin.identity_management.v1.IdentityManagementService.GetGroupsForUser:output_type -> plugin.identity_management.v1.GetGroupsForUserResponse
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_plugin_identity_management_v1_identity_management_proto_init() }
func file_plugin_identity_management_v1_identity_management_proto_init() {
	if File_plugin_identity_management_v1_identity_management_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_identity_management_v1_identity_management_proto_rawDesc), len(file_plugin_identity_management_v1_identity_management_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugin_identity_management_v1_identity_management_proto_goTypes,
		DependencyIndexes: file_plugin_identity_management_v1_identity_management_proto_depIdxs,
		MessageInfos:      file_plugin_identity_management_v1_identity_management_proto_msgTypes,
	}.Build()
	File_plugin_identity_management_v1_identity_management_proto = out.File
	file_plugin_identity_management_v1_identity_management_proto_goTypes = nil
	file_plugin_identity_management_v1_identity_management_proto_depIdxs = nil
}
