// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: plugin/reconciler/v1/reconciler.proto

package reconcilerv1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Reconciler_Reconcile_FullMethodName = "/krypton.reconciler.v1.Reconciler/Reconcile"
)

// ReconcilerClient is the client API for Reconciler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Reconciler is the gRPC contract between Krypton core and an external
// reconciler plugin. Core is the client; the plugin binary is the server.
//
// The plugin receives the raw extension payload for a custom resource kind
// and returns an ExecutionPlan (AST) describing every key operation Krypton
// must perform. The plugin never touches keys or state directly — it only
// declares intent via the JSON-encoded AST. Core is the sole executor.
type ReconcilerClient interface {
	Reconcile(ctx context.Context, in *ReconcileRequest, opts ...grpc.CallOption) (*ReconcileResponse, error)
}

type reconcilerClient struct {
	cc grpc.ClientConnInterface
}

func NewReconcilerClient(cc grpc.ClientConnInterface) ReconcilerClient {
	return &reconcilerClient{cc}
}

func (c *reconcilerClient) Reconcile(ctx context.Context, in *ReconcileRequest, opts ...grpc.CallOption) (*ReconcileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReconcileResponse)
	err := c.cc.Invoke(ctx, Reconciler_Reconcile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReconcilerServer is the server API for Reconciler service.
// All implementations must embed UnimplementedReconcilerServer
// for forward compatibility.
//
// Reconciler is the gRPC contract between Krypton core and an external
// reconciler plugin. Core is the client; the plugin binary is the server.
//
// The plugin receives the raw extension payload for a custom resource kind
// and returns an ExecutionPlan (AST) describing every key operation Krypton
// must perform. The plugin never touches keys or state directly — it only
// declares intent via the JSON-encoded AST. Core is the sole executor.
type ReconcilerServer interface {
	Reconcile(context.Context, *ReconcileRequest) (*ReconcileResponse, error)
	mustEmbedUnimplementedReconcilerServer()
}

// UnimplementedReconcilerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReconcilerServer struct{}

func (UnimplementedReconcilerServer) Reconcile(context.Context, *ReconcileRequest) (*ReconcileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Reconcile not implemented")
}
func (UnimplementedReconcilerServer) mustEmbedUnimplementedReconcilerServer() {}
func (UnimplementedReconcilerServer) testEmbeddedByValue()                    {}

// UnsafeReconcilerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReconcilerServer will
// result in compilation errors.
type UnsafeReconcilerServer interface {
	mustEmbedUnimplementedReconcilerServer()
}

func RegisterReconcilerServer(s grpc.ServiceRegistrar, srv ReconcilerServer) {
	// If the following call panics, it indicates UnimplementedReconcilerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Reconciler_ServiceDesc, srv)
}

func _Reconciler_Reconcile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReconcileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReconcilerServer).Reconcile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Reconciler_Reconcile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReconcilerServer).Reconcile(ctx, req.(*ReconcileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Reconciler_ServiceDesc is the grpc.ServiceDesc for Reconciler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Reconciler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "krypton.reconciler.v1.Reconciler",
	HandlerType: (*ReconcilerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Reconcile",
			Handler:    _Reconciler_Reconcile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin/reconciler/v1/reconciler.proto",
}
