// Code generated by protoc-gen-go-extension. DO NOT EDIT.

package key_material_storagev1

import (
	grpc "google.golang.org/grpc"

	api "github.com/openkcm/plugin-sdk/api"
)

const (
	Type                = "KeyMaterialStorage"
	GRPCServiceFullName = "plugin.key_material_storage.v1.KeyMaterialStorage"
)

func KeyMaterialStoragePluginServer(server KeyMaterialStorageServer) api.PluginServer {
	return keyMaterialStoragePluginServer{KeyMaterialStorageServer: server}
}

type keyMaterialStoragePluginServer struct {
	KeyMaterialStorageServer
}

func (s keyMaterialStoragePluginServer) Type() string {
	return Type
}

func (s keyMaterialStoragePluginServer) GRPCServiceName() string {
	return GRPCServiceFullName
}

func (s keyMaterialStoragePluginServer) RegisterServer(server *grpc.Server) any {
	RegisterKeyMaterialStorageServer(server, s.KeyMaterialStorageServer)
	return s.KeyMaterialStorageServer
}

type KeyMaterialStoragePluginClient struct {
	KeyMaterialStorageClient
}

func (s KeyMaterialStoragePluginClient) Type() string {
	return Type
}

func (c *KeyMaterialStoragePluginClient) IsInitialized() bool {
	return c.KeyMaterialStorageClient != nil
}

func (c *KeyMaterialStoragePluginClient) GRPCServiceName() string {
	return GRPCServiceFullName
}

func (c *KeyMaterialStoragePluginClient) InitClient(conn grpc.ClientConnInterface) any {
	c.KeyMaterialStorageClient = NewKeyMaterialStorageClient(conn)
	return c.KeyMaterialStorageClient
}
