// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: plugin/key_material_storage/v1/key_material_storage.proto

package key_material_storagev1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KeyMaterialStorage_Store_FullMethodName = "/plugin.key_material_storage.v1.KeyMaterialStorage/Store"
	KeyMaterialStorage_Load_FullMethodName  = "/plugin.key_material_storage.v1.KeyMaterialStorage/Load"
)

// KeyMaterialStorageClient is the client API for KeyMaterialStorage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// KeyMaterialStorage defines the universal interface for persisting and
// retrieving opaque blobs of data, typically wrapped key material.
// This allows Krypton to delegate storage to any backend (DB, Vault, File)
// in a completely generic way.
type KeyMaterialStorageClient interface {
	// Store persists a single item. This operation must be idempotent.
	Store(ctx context.Context, in *StoreRequest, opts ...grpc.CallOption) (*StoreResponse, error)
	// Load retrieves a single item by its unique ID.
	Load(ctx context.Context, in *LoadRequest, opts ...grpc.CallOption) (*LoadResponse, error)
}

type keyMaterialStorageClient struct {
	cc grpc.ClientConnInterface
}

func NewKeyMaterialStorageClient(cc grpc.ClientConnInterface) KeyMaterialStorageClient {
	return &keyMaterialStorageClient{cc}
}

func (c *keyMaterialStorageClient) Store(ctx context.Context, in *StoreRequest, opts ...grpc.CallOption) (*StoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoreResponse)
	err := c.cc.Invoke(ctx, KeyMaterialStorage_Store_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyMaterialStorageClient) Load(ctx context.Context, in *LoadRequest, opts ...grpc.CallOption) (*LoadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoadResponse)
	err := c.cc.Invoke(ctx, KeyMaterialStorage_Load_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KeyMaterialStorageServer is the server API for KeyMaterialStorage service.
// All implementations must embed UnimplementedKeyMaterialStorageServer
// for forward compatibility.
//
// KeyMaterialStorage defines the universal interface for persisting and
// retrieving opaque blobs of data, typically wrapped key material.
// This allows Krypton to delegate storage to any backend (DB, Vault, File)
// in a completely generic way.
type KeyMaterialStorageServer interface {
	// Store persists a single item. This operation must be idempotent.
	Store(context.Context, *StoreRequest) (*StoreResponse, error)
	// Load retrieves a single item by its unique ID.
	Load(context.Context, *LoadRequest) (*LoadResponse, error)
	mustEmbedUnimplementedKeyMaterialStorageServer()
}

// UnimplementedKeyMaterialStorageServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKeyMaterialStorageServer struct{}

func (UnimplementedKeyMaterialStorageServer) Store(context.Context, *StoreRequest) (*StoreResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Store not implemented")
}
func (UnimplementedKeyMaterialStorageServer) Load(context.Context, *LoadRequest) (*LoadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Load not implemented")
}
func (UnimplementedKeyMaterialStorageServer) mustEmbedUnimplementedKeyMaterialStorageServer() {}
func (UnimplementedKeyMaterialStorageServer) testEmbeddedByValue()                            {}

// UnsafeKeyMaterialStorageServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KeyMaterialStorageServer will
// result in compilation errors.
type UnsafeKeyMaterialStorageServer interface {
	mustEmbedUnimplementedKeyMaterialStorageServer()
}

func RegisterKeyMaterialStorageServer(s grpc.ServiceRegistrar, srv KeyMaterialStorageServer) {
	// If the following call panics, it indicates UnimplementedKeyMaterialStorageServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KeyMaterialStorage_ServiceDesc, srv)
}

func _KeyMaterialStorage_Store_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyMaterialStorageServer).Store(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyMaterialStorage_Store_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyMaterialStorageServer).Store(ctx, req.(*StoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyMaterialStorage_Load_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyMaterialStorageServer).Load(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyMaterialStorage_Load_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyMaterialStorageServer).Load(ctx, req.(*LoadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KeyMaterialStorage_ServiceDesc is the grpc.ServiceDesc for KeyMaterialStorage service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KeyMaterialStorage_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "plugin.key_material_storage.v1.KeyMaterialStorage",
	HandlerType: (*KeyMaterialStorageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Store",
			Handler:    _KeyMaterialStorage_Store_Handler,
		},
		{
			MethodName: "Load",
			Handler:    _KeyMaterialStorage_Load_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin/key_material_storage/v1/key_material_storage.proto",
}
