// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: plugin/key_material_storage/v1/key_material_storage.proto

package key_material_storagev1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// KeyMaterial represents a single unit of stored data.
type KeyMaterial struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Tags          map[string]string      `protobuf:"bytes,10,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyMaterial) Reset() {
	*x = KeyMaterial{}
	mi := &file_plugin_key_material_storage_v1_key_material_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyMaterial) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyMaterial) ProtoMessage() {}

func (x *KeyMaterial) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_key_material_storage_v1_key_material_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyMaterial.ProtoReflect.Descriptor instead.
func (*KeyMaterial) Descriptor() ([]byte, []int) {
	return file_plugin_key_material_storage_v1_key_material_storage_proto_rawDescGZIP(), []int{0}
}

func (x *KeyMaterial) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *KeyMaterial) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *KeyMaterial) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *KeyMaterial) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type Filter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    *Filter_StringMatch    `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	// Filter by cryptographic algorithm (e.g., "AES-256-GCM").
	Algorithm *string `protobuf:"bytes,2,opt,name=algorithm,proto3,oneof" json:"algorithm,omitempty"`
	// Filter by metadata tags (e.g., {"env": "prod"}).
	// Match is typically performed as "contains all".
	Tags          map[string]string `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAt     *Filter_TimeRange `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3,oneof" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Filter) Reset() {
	*x = Filter{}
	mi := &file_plugin_key_material_storage_v1_key_material_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_key_material_storage_v1_key_material_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_plugin_key_material_storage_v1_key_material_storage_proto_rawDescGZIP(), []int{1}
}

func (x *Filter) GetId() *Filter_StringMatch {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Filter) GetAlgorithm() string {
	if x != nil && x.Algorithm != nil {
		return *x.Algorithm
	}
	return ""
}

func (x *Filter) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Filter) GetCreatedAt() *Filter_TimeRange {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ListIDsRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Namespace string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Filter    *Filter                `protobuf:"bytes,2,opt,name=filter,proto3,oneof" json:"filter,omitempty"`
	// Pagination support
	PageSize      uint32 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIDsRequest) Reset() {
	*x = ListIDsRequest{}
	mi := &file_plugin_key_material_storage_v1_key_material_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIDsRequest) ProtoMessage() {}

func (x *ListIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_key_material_storage_v1_key_material_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIDsRequest.ProtoReflect.Descriptor instead.
func (*ListIDsRequest) Descriptor() ([]byte, []int) {
	return file_plugin_key_material_storage_v1_key_material_storage_proto_rawDescGZIP(), []int{2}
}

func (x *ListIDsRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ListIDsRequest) GetFilter() *Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *ListIDsRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListIDsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListIDsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIDsResponse) Reset() {
	*x = ListIDsResponse{}
	mi := &file_plugin_key_material_storage_v1_key_material_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIDsResponse) ProtoMessage() {}

func (x *ListIDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_key_material_storage_v1_key_material_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIDsResponse.ProtoReflect.Descriptor instead.
func (*ListIDsResponse) Descriptor() ([]byte, []int) {
	return file_plugin_key_material_storage_v1_key_material_storage_proto_rawDescGZIP(), []int{3}
}

func (x *ListIDsResponse) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *ListIDsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type StoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	KeyMaterial   *KeyMaterial           `protobuf:"bytes,2,opt,name=key_material,json=keyMaterial,proto3" json:"key_material,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreRequest) Reset() {
	*x = StoreRequest{}
	mi := &file_plugin_key_material_storage_v1_key_material_storage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreRequest) ProtoMessage() {}

func (x *StoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_key_material_storage_v1_key_material_storage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreRequest.ProtoReflect.Descriptor instead.
func (*StoreRequest) Descriptor() ([]byte, []int) {
	return file_plugin_key_material_storage_v1_key_material_storage_proto_rawDescGZIP(), []int{4}
}

func (x *StoreRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *StoreRequest) GetKeyMaterial() *KeyMaterial {
	if x != nil {
		return x.KeyMaterial
	}
	return nil
}

type StoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreResponse) Reset() {
	*x = StoreResponse{}
	mi := &file_plugin_key_material_storage_v1_key_material_storage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreResponse) ProtoMessage() {}

func (x *StoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_key_material_storage_v1_key_material_storage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreResponse.ProtoReflect.Descriptor instead.
func (*StoreResponse) Descriptor() ([]byte, []int) {
	return file_plugin_key_material_storage_v1_key_material_storage_proto_rawDescGZIP(), []int{5}
}

type LoadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadRequest) Reset() {
	*x = LoadRequest{}
	mi := &file_plugin_key_material_storage_v1_key_material_storage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadRequest) ProtoMessage() {}

func (x *LoadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_key_material_storage_v1_key_material_storage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadRequest.ProtoReflect.Descriptor instead.
func (*LoadRequest) Descriptor() ([]byte, []int) {
	return file_plugin_key_material_storage_v1_key_material_storage_proto_rawDescGZIP(), []int{6}
}

func (x *LoadRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *LoadRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type LoadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyMaterial   *KeyMaterial           `protobuf:"bytes,1,opt,name=key_material,json=keyMaterial,proto3" json:"key_material,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadResponse) Reset() {
	*x = LoadResponse{}
	mi := &file_plugin_key_material_storage_v1_key_material_storage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadResponse) ProtoMessage() {}

func (x *LoadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_key_material_storage_v1_key_material_storage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadResponse.ProtoReflect.Descriptor instead.
func (*LoadResponse) Descriptor() ([]byte, []int) {
	return file_plugin_key_material_storage_v1_key_material_storage_proto_rawDescGZIP(), []int{7}
}

func (x *LoadResponse) GetKeyMaterial() *KeyMaterial {
	if x != nil {
		return x.KeyMaterial
	}
	return nil
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_plugin_key_material_storage_v1_key_material_storage_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_key_material_storage_v1_key_material_storage_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_plugin_key_material_storage_v1_key_material_storage_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *DeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_plugin_key_material_storage_v1_key_material_storage_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_key_material_storage_v1_key_material_storage_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_plugin_key_material_storage_v1_key_material_storage_proto_rawDescGZIP(), []int{9}
}

// Pattern-based matching for the primary Key ID.
type Filter_StringMatch struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Type:
	//
	//	*Filter_StringMatch_Prefix
	//	*Filter_StringMatch_Suffix
	//	*Filter_StringMatch_Contains
	//	*Filter_StringMatch_Exact
	Type          isFilter_StringMatch_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Filter_StringMatch) Reset() {
	*x = Filter_StringMatch{}
	mi := &file_plugin_key_material_storage_v1_key_material_storage_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filter_StringMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter_StringMatch) ProtoMessage() {}

func (x *Filter_StringMatch) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_key_material_storage_v1_key_material_storage_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter_StringMatch.ProtoReflect.Descriptor instead.
func (*Filter_StringMatch) Descriptor() ([]byte, []int) {
	return file_plugin_key_material_storage_v1_key_material_storage_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Filter_StringMatch) GetType() isFilter_StringMatch_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *Filter_StringMatch) GetPrefix() string {
	if x != nil {
		if x, ok := x.Type.(*Filter_StringMatch_Prefix); ok {
			return x.Prefix
		}
	}
	return ""
}

func (x *Filter_StringMatch) GetSuffix() string {
	if x != nil {
		if x, ok := x.Type.(*Filter_StringMatch_Suffix); ok {
			return x.Suffix
		}
	}
	return ""
}

func (x *Filter_StringMatch) GetContains() string {
	if x != nil {
		if x, ok := x.Type.(*Filter_StringMatch_Contains); ok {
			return x.Contains
		}
	}
	return ""
}

func (x *Filter_StringMatch) GetExact() string {
	if x != nil {
		if x, ok := x.Type.(*Filter_StringMatch_Exact); ok {
			return x.Exact
		}
	}
	return ""
}

type isFilter_StringMatch_Type interface {
	isFilter_StringMatch_Type()
}

type Filter_StringMatch_Prefix struct {
	Prefix string `protobuf:"bytes,1,opt,name=prefix,proto3,oneof"`
}

type Filter_StringMatch_Suffix struct {
	Suffix string `protobuf:"bytes,2,opt,name=suffix,proto3,oneof"`
}

type Filter_StringMatch_Contains struct {
	Contains string `protobuf:"bytes,3,opt,name=contains,proto3,oneof"`
}

type Filter_StringMatch_Exact struct {
	Exact string `protobuf:"bytes,4,opt,name=exact,proto3,oneof"`
}

func (*Filter_StringMatch_Prefix) isFilter_StringMatch_Type() {}

func (*Filter_StringMatch_Suffix) isFilter_StringMatch_Type() {}

func (*Filter_StringMatch_Contains) isFilter_StringMatch_Type() {}

func (*Filter_StringMatch_Exact) isFilter_StringMatch_Type() {}

// Filter by the time the key was created.
type Filter_TimeRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Filter_TimeRange) Reset() {
	*x = Filter_TimeRange{}
	mi := &file_plugin_key_material_storage_v1_key_material_storage_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filter_TimeRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter_TimeRange) ProtoMessage() {}

func (x *Filter_TimeRange) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_key_material_storage_v1_key_material_storage_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter_TimeRange.ProtoReflect.Descriptor instead.
func (*Filter_TimeRange) Descriptor() ([]byte, []int) {
	return file_plugin_key_material_storage_v1_key_material_storage_proto_rawDescGZIP(), []int{1, 2}
}

func (x *Filter_TimeRange) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *Filter_TimeRange) GetTo() *timestamppb.Timestamp {
	if x != nil {
		return x.To
	}
	return nil
}

var File_plugin_key_material_storage_v1_key_material_storage_proto protoreflect.FileDescriptor

const file_plugin_key_material_storage_v1_key_material_storage_proto_rawDesc = "" +
	"\n" +
	"9plugin/key_material_storage/v1/key_material_storage.proto\x12&krypton.plugin.key_material_storage.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8a\x02\n" +
	"\vKeyMaterial\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x02id\x12\x1b\n" +
	"\x04data\x18\x02 \x01(\fB\a\xbaH\x04z\x02\x10\x01R\x04data\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12Q\n" +
	"\x04tags\x18\n" +
	" \x03(\v2=.krypton.plugin.key_material_storage.v1.KeyMaterial.TagsEntryR\x04tags\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xef\x04\n" +
	"\x06Filter\x12O\n" +
	"\x02id\x18\x01 \x01(\v2:.krypton.plugin.key_material_storage.v1.Filter.StringMatchH\x00R\x02id\x88\x01\x01\x12!\n" +
	"\talgorithm\x18\x02 \x01(\tH\x01R\talgorithm\x88\x01\x01\x12L\n" +
	"\x04tags\x18\x03 \x03(\v28.krypton.plugin.key_material_storage.v1.Filter.TagsEntryR\x04tags\x12\\\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v28.krypton.plugin.key_material_storage.v1.Filter.TimeRangeH\x02R\tcreatedAt\x88\x01\x01\x1a\x7f\n" +
	"\vStringMatch\x12\x18\n" +
	"\x06prefix\x18\x01 \x01(\tH\x00R\x06prefix\x12\x18\n" +
	"\x06suffix\x18\x02 \x01(\tH\x00R\x06suffix\x12\x1c\n" +
	"\bcontains\x18\x03 \x01(\tH\x00R\bcontains\x12\x16\n" +
	"\x05exact\x18\x04 \x01(\tH\x00R\x05exactB\x06\n" +
	"\x04type\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1ag\n" +
	"\tTimeRange\x12.\n" +
	"\x04from\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04from\x12*\n" +
	"\x02to\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x02toB\x05\n" +
	"\x03_idB\f\n" +
	"\n" +
	"_algorithmB\r\n" +
	"\v_created_at\"\xcb\x01\n" +
	"\x0eListIDsRequest\x12%\n" +
	"\tnamespace\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\tnamespace\x12K\n" +
	"\x06filter\x18\x02 \x01(\v2..krypton.plugin.key_material_storage.v1.FilterH\x00R\x06filter\x88\x01\x01\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\rR\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tR\tpageTokenB\t\n" +
	"\a_filter\"K\n" +
	"\x0fListIDsResponse\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\x95\x01\n" +
	"\fStoreRequest\x12%\n" +
	"\tnamespace\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\tnamespace\x12^\n" +
	"\fkey_material\x18\x02 \x01(\v23.krypton.plugin.key_material_storage.v1.KeyMaterialB\x06\xbaH\x03\xc8\x01\x01R\vkeyMaterial\"\x0f\n" +
	"\rStoreResponse\"M\n" +
	"\vLoadRequest\x12%\n" +
	"\tnamespace\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\tnamespace\x12\x17\n" +
	"\x02id\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x02id\"f\n" +
	"\fLoadResponse\x12V\n" +
	"\fkey_material\x18\x01 \x01(\v23.krypton.plugin.key_material_storage.v1.KeyMaterialR\vkeyMaterial\"O\n" +
	"\rDeleteRequest\x12%\n" +
	"\tnamespace\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\tnamespace\x12\x17\n" +
	"\x02id\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x02id\"\x10\n" +
	"\x0eDeleteResponse2\xf4\x03\n" +
	"\x12KeyMaterialStorage\x12t\n" +
	"\x05Store\x124.krypton.plugin.key_material_storage.v1.StoreRequest\x1a5.krypton.plugin.key_material_storage.v1.StoreResponse\x12q\n" +
	"\x04Load\x123.krypton.plugin.key_material_storage.v1.LoadRequest\x1a4.krypton.plugin.key_material_storage.v1.LoadResponse\x12w\n" +
	"\x06Delete\x125.krypton.plugin.key_material_storage.v1.DeleteRequest\x1a6.krypton.plugin.key_material_storage.v1.DeleteResponse\x12|\n" +
	"\aListIDs\x126.krypton.plugin.key_material_storage.v1.ListIDsRequest\x1a7.krypton.plugin.key_material_storage.v1.ListIDsResponse0\x01B\xd3\x02\n" +
	"*com.krypton.plugin.key_material_storage.v1B\x17KeyMaterialStorageProtoP\x01ZYgithub.com/openkcm/plugin-sdk/proto/plugin/key_material_storage/v1;key_material_storagev1\xa2\x02\x03KPK\xaa\x02$Krypton.Plugin.KeyMaterialStorage.V1\xca\x02$Krypton\\Plugin\\KeyMaterialStorage\\V1\xe2\x020Krypton\\Plugin\\KeyMaterialStorage\\V1\\GPBMetadata\xea\x02'Krypton::Plugin::KeyMaterialStorage::V1b\x06proto3"

var (
	file_plugin_key_material_storage_v1_key_material_storage_proto_rawDescOnce sync.Once
	file_plugin_key_material_storage_v1_key_material_storage_proto_rawDescData []byte
)

func file_plugin_key_material_storage_v1_key_material_storage_proto_rawDescGZIP() []byte {
	file_plugin_key_material_storage_v1_key_material_storage_proto_rawDescOnce.Do(func() {
		file_plugin_key_material_storage_v1_key_material_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_key_material_storage_v1_key_material_storage_proto_rawDesc), len(file_plugin_key_material_storage_v1_key_material_storage_proto_rawDesc)))
	})
	return file_plugin_key_material_storage_v1_key_material_storage_proto_rawDescData
}

var file_plugin_key_material_storage_v1_key_material_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_plugin_key_material_storage_v1_key_material_storage_proto_goTypes = []any{
	(*KeyMaterial)(nil),           // 0: krypton.plugin.key_material_storage.v1.KeyMaterial
	(*Filter)(nil),                // 1: krypton.plugin.key_material_storage.v1.Filter
	(*ListIDsRequest)(nil),        // 2: krypton.plugin.key_material_storage.v1.ListIDsRequest
	(*ListIDsResponse)(nil),       // 3: krypton.plugin.key_material_storage.v1.ListIDsResponse
	(*StoreRequest)(nil),          // 4: krypton.plugin.key_material_storage.v1.StoreRequest
	(*StoreResponse)(nil),         // 5: krypton.plugin.key_material_storage.v1.StoreResponse
	(*LoadRequest)(nil),           // 6: krypton.plugin.key_material_storage.v1.LoadRequest
	(*LoadResponse)(nil),          // 7: krypton.plugin.key_material_storage.v1.LoadResponse
	(*DeleteRequest)(nil),         // 8: krypton.plugin.key_material_storage.v1.DeleteRequest
	(*DeleteResponse)(nil),        // 9: krypton.plugin.key_material_storage.v1.DeleteResponse
	nil,                           // 10: krypton.plugin.key_material_storage.v1.KeyMaterial.TagsEntry
	(*Filter_StringMatch)(nil),    // 11: krypton.plugin.key_material_storage.v1.Filter.StringMatch
	nil,                           // 12: krypton.plugin.key_material_storage.v1.Filter.TagsEntry
	(*Filter_TimeRange)(nil),      // 13: krypton.plugin.key_material_storage.v1.Filter.TimeRange
	(*timestamppb.Timestamp)(nil), // 14: google.protobuf.Timestamp
}
var file_plugin_key_material_storage_v1_key_material_storage_proto_depIdxs = []int32{
	14, // 0: krypton.plugin.key_material_storage.v1.KeyMaterial.created_at:type_name -> google.protobuf.Timestamp
	10, // 1: krypton.plugin.key_material_storage.v1.KeyMaterial.tags:type_name -> krypton.plugin.key_material_storage.v1.KeyMaterial.TagsEntry
	11, // 2: krypton.plugin.key_material_storage.v1.Filter.id:type_name -> krypton.plugin.key_material_storage.v1.Filter.StringMatch
	12, // 3: krypton.plugin.key_material_storage.v1.Filter.tags:type_name -> krypton.plugin.key_material_storage.v1.Filter.TagsEntry
	13, // 4: krypton.plugin.key_material_storage.v1.Filter.created_at:type_name -> krypton.plugin.key_material_storage.v1.Filter.TimeRange
	1,  // 5: krypton.plugin.key_material_storage.v1.ListIDsRequest.filter:type_name -> krypton.plugin.key_material_storage.v1.Filter
	0,  // 6: krypton.plugin.key_material_storage.v1.StoreRequest.key_material:type_name -> krypton.plugin.key_material_storage.v1.KeyMaterial
	0,  // 7: krypton.plugin.key_material_storage.v1.LoadResponse.key_material:type_name -> krypton.plugin.key_material_storage.v1.KeyMaterial
	14, // 8: krypton.plugin.key_material_storage.v1.Filter.TimeRange.from:type_name -> google.protobuf.Timestamp
	14, // 9: krypton.plugin.key_material_storage.v1.Filter.TimeRange.to:type_name -> google.protobuf.Timestamp
	4,  // 10: krypton.plugin.key_material_storage.v1.KeyMaterialStorage.Store:input_type -> krypton.plugin.key_material_storage.v1.StoreRequest
	6,  // 11: krypton.plugin.key_material_storage.v1.KeyMaterialStorage.Load:input_type -> krypton.plugin.key_material_storage.v1.LoadRequest
	8,  // 12: krypton.plugin.key_material_storage.v1.KeyMaterialStorage.Delete:input_type -> krypton.plugin.key_material_storage.v1.DeleteRequest
	2,  // 13: krypton.plugin.key_material_storage.v1.KeyMaterialStorage.ListIDs:input_type -> krypton.plugin.key_material_storage.v1.ListIDsRequest
	5,  // 14: krypton.plugin.key_material_storage.v1.KeyMaterialStorage.Store:output_type -> krypton.plugin.key_material_storage.v1.StoreResponse
	7,  // 15: krypton.plugin.key_material_storage.v1.KeyMaterialStorage.Load:output_type -> krypton.plugin.key_material_storage.v1.LoadResponse
	9,  // 16: krypton.plugin.key_material_storage.v1.KeyMaterialStorage.Delete:output_type -> krypton.plugin.key_material_storage.v1.DeleteResponse
	3,  // 17: krypton.plugin.key_material_storage.v1.KeyMaterialStorage.ListIDs:output_type -> krypton.plugin.key_material_storage.v1.ListIDsResponse
	14, // [14:18] is the sub-list for method output_type
	10, // [10:14] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_plugin_key_material_storage_v1_key_material_storage_proto_init() }
func file_plugin_key_material_storage_v1_key_material_storage_proto_init() {
	if File_plugin_key_material_storage_v1_key_material_storage_proto != nil {
		return
	}
	file_plugin_key_material_storage_v1_key_material_storage_proto_msgTypes[1].OneofWrappers = []any{}
	file_plugin_key_material_storage_v1_key_material_storage_proto_msgTypes[2].OneofWrappers = []any{}
	file_plugin_key_material_storage_v1_key_material_storage_proto_msgTypes[11].OneofWrappers = []any{
		(*Filter_StringMatch_Prefix)(nil),
		(*Filter_StringMatch_Suffix)(nil),
		(*Filter_StringMatch_Contains)(nil),
		(*Filter_StringMatch_Exact)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_key_material_storage_v1_key_material_storage_proto_rawDesc), len(file_plugin_key_material_storage_v1_key_material_storage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugin_key_material_storage_v1_key_material_storage_proto_goTypes,
		DependencyIndexes: file_plugin_key_material_storage_v1_key_material_storage_proto_depIdxs,
		MessageInfos:      file_plugin_key_material_storage_v1_key_material_storage_proto_msgTypes,
	}.Build()
	File_plugin_key_material_storage_v1_key_material_storage_proto = out.File
	file_plugin_key_material_storage_v1_key_material_storage_proto_goTypes = nil
	file_plugin_key_material_storage_v1_key_material_storage_proto_depIdxs = nil
}
