// Code generated by protoc-gen-go-extension. DO NOT EDIT.

package keystore_managementv1

import (
	grpc "google.golang.org/grpc"

	api "github.com/openkcm/plugin-sdk/api"
)

const (
	Type                = "KeystoreManagement"
	GRPCServiceFullName = "plugin.keystore_management.v1.KeystoreManagement"
)

func KeystoreManagementPluginServer(server KeystoreManagementServer) api.PluginServer {
	return keystoreManagementPluginServer{KeystoreManagementServer: server}
}

type keystoreManagementPluginServer struct {
	KeystoreManagementServer
}

func (s keystoreManagementPluginServer) Type() string {
	return Type
}

func (s keystoreManagementPluginServer) GRPCServiceName() string {
	return GRPCServiceFullName
}

func (s keystoreManagementPluginServer) RegisterServer(server *grpc.Server) any {
	RegisterKeystoreManagementServer(server, s.KeystoreManagementServer)
	return s.KeystoreManagementServer
}

type KeystoreManagementPluginClient struct {
	KeystoreManagementClient
}

func (s KeystoreManagementPluginClient) Type() string {
	return Type
}

func (c *KeystoreManagementPluginClient) IsInitialized() bool {
	return c.KeystoreManagementClient != nil
}

func (c *KeystoreManagementPluginClient) GRPCServiceName() string {
	return GRPCServiceFullName
}

func (c *KeystoreManagementPluginClient) InitClient(conn grpc.ClientConnInterface) any {
	c.KeystoreManagementClient = NewKeystoreManagementClient(conn)
	return c.KeystoreManagementClient
}
