// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: plugin/notification/v1/notification.proto

package notificationv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NotificationType int32

const (
	NotificationType_NOTIFICATION_TYPE_UNSPECIFIED NotificationType = 0 // Unspecified notification type
	NotificationType_NOTIFICATION_TYPE_EMAIL       NotificationType = 1 // Email notification
	NotificationType_NOTIFICATION_TYPE_TEXT        NotificationType = 2 // Text message notification
	NotificationType_NOTIFICATION_TYPE_WEB         NotificationType = 3 // Web notification
)

// Enum value maps for NotificationType.
var (
	NotificationType_name = map[int32]string{
		0: "NOTIFICATION_TYPE_UNSPECIFIED",
		1: "NOTIFICATION_TYPE_EMAIL",
		2: "NOTIFICATION_TYPE_TEXT",
		3: "NOTIFICATION_TYPE_WEB",
	}
	NotificationType_value = map[string]int32{
		"NOTIFICATION_TYPE_UNSPECIFIED": 0,
		"NOTIFICATION_TYPE_EMAIL":       1,
		"NOTIFICATION_TYPE_TEXT":        2,
		"NOTIFICATION_TYPE_WEB":         3,
	}
)

func (x NotificationType) Enum() *NotificationType {
	p := new(NotificationType)
	*p = x
	return p
}

func (x NotificationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationType) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_notification_v1_notification_proto_enumTypes[0].Descriptor()
}

func (NotificationType) Type() protoreflect.EnumType {
	return &file_plugin_notification_v1_notification_proto_enumTypes[0]
}

func (x NotificationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationType.Descriptor instead.
func (NotificationType) EnumDescriptor() ([]byte, []int) {
	return file_plugin_notification_v1_notification_proto_rawDescGZIP(), []int{0}
}

type SendNotificationRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	NotificationType NotificationType       `protobuf:"varint,1,opt,name=notification_type,json=notificationType,proto3,enum=plugin.notification.v1.NotificationType" json:"notification_type,omitempty"` // Type of notification (e.g., Email, Text, Web)
	Recipients       []string               `protobuf:"bytes,2,rep,name=recipients,proto3" json:"recipients,omitempty"`                                                                                   // List of recipient addresses
	Subject          string                 `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`                                                                                         // Subject of the notification
	Body             string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`                                                                                               // Body of the notification (HTML or Raw)
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SendNotificationRequest) Reset() {
	*x = SendNotificationRequest{}
	mi := &file_plugin_notification_v1_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNotificationRequest) ProtoMessage() {}

func (x *SendNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_notification_v1_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNotificationRequest.ProtoReflect.Descriptor instead.
func (*SendNotificationRequest) Descriptor() ([]byte, []int) {
	return file_plugin_notification_v1_notification_proto_rawDescGZIP(), []int{0}
}

func (x *SendNotificationRequest) GetNotificationType() NotificationType {
	if x != nil {
		return x.NotificationType
	}
	return NotificationType_NOTIFICATION_TYPE_UNSPECIFIED
}

func (x *SendNotificationRequest) GetRecipients() []string {
	if x != nil {
		return x.Recipients
	}
	return nil
}

func (x *SendNotificationRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *SendNotificationRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type SendNotificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // Indicates if the notification was sent successfully
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // Additional message or error details
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendNotificationResponse) Reset() {
	*x = SendNotificationResponse{}
	mi := &file_plugin_notification_v1_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNotificationResponse) ProtoMessage() {}

func (x *SendNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_notification_v1_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNotificationResponse.ProtoReflect.Descriptor instead.
func (*SendNotificationResponse) Descriptor() ([]byte, []int) {
	return file_plugin_notification_v1_notification_proto_rawDescGZIP(), []int{1}
}

func (x *SendNotificationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendNotificationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_plugin_notification_v1_notification_proto protoreflect.FileDescriptor

const file_plugin_notification_v1_notification_proto_rawDesc = "" +
	"\n" +
	")plugin/notification/v1/notification.proto\x12\x16plugin.notification.v1\"\xbe\x01\n" +
	"\x17SendNotificationRequest\x12U\n" +
	"\x11notification_type\x18\x01 \x01(\x0e2(.plugin.notification.v1.NotificationTypeR\x10notificationType\x12\x1e\n" +
	"\n" +
	"recipients\x18\x02 \x03(\tR\n" +
	"recipients\x12\x18\n" +
	"\asubject\x18\x03 \x01(\tR\asubject\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\"N\n" +
	"\x18SendNotificationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*\x89\x01\n" +
	"\x10NotificationType\x12!\n" +
	"\x1dNOTIFICATION_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17NOTIFICATION_TYPE_EMAIL\x10\x01\x12\x1a\n" +
	"\x16NOTIFICATION_TYPE_TEXT\x10\x02\x12\x19\n" +
	"\x15NOTIFICATION_TYPE_WEB\x10\x032\x8c\x01\n" +
	"\x13NotificationService\x12u\n" +
	"\x10SendNotification\x12/.plugin.notification.v1.SendNotificationRequest\x1a0.plugin.notification.v1.SendNotificationResponseB\xf4\x01\n" +
	"\x1acom.plugin.notification.v1B\x11NotificationProtoP\x01ZIgithub.com/openkcm/plugin-sdk/proto/plugin/notification/v1;notificationv1\xa2\x02\x03PNX\xaa\x02\x16Plugin.Notification.V1\xca\x02\x16Plugin\\Notification\\V1\xe2\x02\"Plugin\\Notification\\V1\\GPBMetadata\xea\x02\x18Plugin::Notification::V1b\x06proto3"

var (
	file_plugin_notification_v1_notification_proto_rawDescOnce sync.Once
	file_plugin_notification_v1_notification_proto_rawDescData []byte
)

func file_plugin_notification_v1_notification_proto_rawDescGZIP() []byte {
	file_plugin_notification_v1_notification_proto_rawDescOnce.Do(func() {
		file_plugin_notification_v1_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_notification_v1_notification_proto_rawDesc), len(file_plugin_notification_v1_notification_proto_rawDesc)))
	})
	return file_plugin_notification_v1_notification_proto_rawDescData
}

var file_plugin_notification_v1_notification_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_plugin_notification_v1_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_plugin_notification_v1_notification_proto_goTypes = []any{
	(NotificationType)(0),            // 0: plugin.notification.v1.NotificationType
	(*SendNotificationRequest)(nil),  // 1: plugin.notification.v1.SendNotificationRequest
	(*SendNotificationResponse)(nil), // 2: plugin.notification.v1.SendNotificationResponse
}
var file_plugin_notification_v1_notification_proto_depIdxs = []int32{
	0, // 0: plugin.notification.v1.SendNotificationRequest.notification_type:type_name -> plugin.notification.v1.NotificationType
	1, // 1: plugin.notification.v1.NotificationService.SendNotification:input_type -> plugin.notification.v1.SendNotificationRequest
	2, // 2: plugin.notification.v1.NotificationService.SendNotification:output_type -> plugin.notification.v1.SendNotificationResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_plugin_notification_v1_notification_proto_init() }
func file_plugin_notification_v1_notification_proto_init() {
	if File_plugin_notification_v1_notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_notification_v1_notification_proto_rawDesc), len(file_plugin_notification_v1_notification_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugin_notification_v1_notification_proto_goTypes,
		DependencyIndexes: file_plugin_notification_v1_notification_proto_depIdxs,
		EnumInfos:         file_plugin_notification_v1_notification_proto_enumTypes,
		MessageInfos:      file_plugin_notification_v1_notification_proto_msgTypes,
	}.Build()
	File_plugin_notification_v1_notification_proto = out.File
	file_plugin_notification_v1_notification_proto_goTypes = nil
	file_plugin_notification_v1_notification_proto_depIdxs = nil
}
