// Code generated by protoc-gen-go-extension. DO NOT EDIT.

package notificationv1

import (
	api "github.com/openkcm/plugin-sdk/api"
	grpc "google.golang.org/grpc"
)

const (
	Type                = "Notification"
	GRPCServiceFullName = "plugin.notification.v1.Notification"
)

func NotificationPluginServer(server NotificationServer) api.PluginServer {
	return notificationPluginServer{NotificationServer: server}
}

type notificationPluginServer struct {
	NotificationServer
}

func (s notificationPluginServer) Type() string {
	return Type
}

func (s notificationPluginServer) GRPCServiceName() string {
	return GRPCServiceFullName
}

func (s notificationPluginServer) RegisterServer(server *grpc.Server) any {
	RegisterNotificationServer(server, s.NotificationServer)
	return s.NotificationServer
}

type NotificationPluginClient struct {
	NotificationClient
}

func (s NotificationPluginClient) Type() string {
	return Type
}

func (c *NotificationPluginClient) IsInitialized() bool {
	return c.NotificationClient != nil
}

func (c *NotificationPluginClient) GRPCServiceName() string {
	return GRPCServiceFullName
}

func (c *NotificationPluginClient) InitClient(conn grpc.ClientConnInterface) any {
	c.NotificationClient = NewNotificationClient(conn)
	return c.NotificationClient
}
