// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: plugin/cipher_wrapper/v1/cipher_wrapper.proto

package cipher_wrapperv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WrapRequest contains the raw key material and the context needed to encrypt it.
type WrapRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// REQUIRED: The raw cryptographic material to be wrapped.
	Plaintext []byte `protobuf:"bytes,1,opt,name=plaintext,proto3" json:"plaintext,omitempty"`
	// REQUIRED: The universal locator for the cryptographic key (ARN, URI, or Path).
	KeyUri string `protobuf:"bytes,2,opt,name=key_uri,json=keyUri,proto3" json:"key_uri,omitempty"`
	// OPTIONAL: Standard Additional Authenticated Data (AAD) byte buffer.
	// Explicitly marked optional so the Go plugin can check `if req.Aad != nil`.
	Aad []byte `protobuf:"bytes,3,opt,name=aad,proto3,oneof" json:"aad,omitempty"`
	// OPTIONAL (Map): Key-Value Encryption Context (used by AWS/GCP/Alibaba).
	// Maps cannot use the 'optional' keyword in proto3, but are implicitly optional.
	EncryptionContext map[string]string `protobuf:"bytes,4,rep,name=encryption_context,json=encryptionContext,proto3" json:"encryption_context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// OPTIONAL: The explicit cryptographic wrapping mechanism (e.g., "RSA-OAEP-256").
	// Required for Azure and HSMs, safely omitted for AWS/Vault.
	Mechanism *string `protobuf:"bytes,5,opt,name=mechanism,proto3,oneof" json:"mechanism,omitempty"`
	// OPTIONAL: Initialization Vector (IV) or Nonce.
	// Provided only if the CMK core is dictating the IV to an HSM.
	Iv []byte `protobuf:"bytes,6,opt,name=iv,proto3,oneof" json:"iv,omitempty"`
	// OPTIONAL (Map): Dynamic Configuration Pass-through.
	Options       map[string]string `protobuf:"bytes,7,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WrapRequest) Reset() {
	*x = WrapRequest{}
	mi := &file_plugin_cipher_wrapper_v1_cipher_wrapper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WrapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WrapRequest) ProtoMessage() {}

func (x *WrapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_cipher_wrapper_v1_cipher_wrapper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WrapRequest.ProtoReflect.Descriptor instead.
func (*WrapRequest) Descriptor() ([]byte, []int) {
	return file_plugin_cipher_wrapper_v1_cipher_wrapper_proto_rawDescGZIP(), []int{0}
}

func (x *WrapRequest) GetPlaintext() []byte {
	if x != nil {
		return x.Plaintext
	}
	return nil
}

func (x *WrapRequest) GetKeyUri() string {
	if x != nil {
		return x.KeyUri
	}
	return ""
}

func (x *WrapRequest) GetAad() []byte {
	if x != nil {
		return x.Aad
	}
	return nil
}

func (x *WrapRequest) GetEncryptionContext() map[string]string {
	if x != nil {
		return x.EncryptionContext
	}
	return nil
}

func (x *WrapRequest) GetMechanism() string {
	if x != nil && x.Mechanism != nil {
		return *x.Mechanism
	}
	return ""
}

func (x *WrapRequest) GetIv() []byte {
	if x != nil {
		return x.Iv
	}
	return nil
}

func (x *WrapRequest) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

// WrapResponse returns the provider-specific ciphertext and metadata.
type WrapResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// REQUIRED: The opaque, vendor-specific ciphertext.
	Ciphertext []byte `protobuf:"bytes,1,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	// OPTIONAL: The exact key version ID used during the operation.
	// Some providers (like HSMs) do not have a concept of version IDs.
	KeyVersionId *string `protobuf:"bytes,2,opt,name=key_version_id,json=keyVersionId,proto3,oneof" json:"key_version_id,omitempty"`
	// OPTIONAL: The Initialization Vector generated by the provider.
	// Returned only if the provider generated it and CMK needs to store it.
	Iv []byte `protobuf:"bytes,3,opt,name=iv,proto3,oneof" json:"iv,omitempty"`
	// OPTIONAL (Map): Vendor-specific metadata.
	Metadata      map[string]string `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WrapResponse) Reset() {
	*x = WrapResponse{}
	mi := &file_plugin_cipher_wrapper_v1_cipher_wrapper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WrapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WrapResponse) ProtoMessage() {}

func (x *WrapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_cipher_wrapper_v1_cipher_wrapper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WrapResponse.ProtoReflect.Descriptor instead.
func (*WrapResponse) Descriptor() ([]byte, []int) {
	return file_plugin_cipher_wrapper_v1_cipher_wrapper_proto_rawDescGZIP(), []int{1}
}

func (x *WrapResponse) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

func (x *WrapResponse) GetKeyVersionId() string {
	if x != nil && x.KeyVersionId != nil {
		return *x.KeyVersionId
	}
	return ""
}

func (x *WrapResponse) GetIv() []byte {
	if x != nil {
		return x.Iv
	}
	return nil
}

func (x *WrapResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// UnwrapRequest contains the opaque ciphertext and the exact parameters
// originally used during the Wrap operation.
type UnwrapRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// REQUIRED: The opaque ciphertext retrieved from the CMK persistent storage.
	Ciphertext []byte `protobuf:"bytes,1,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	// REQUIRED: The universal locator for the cryptographic key.
	KeyUri string `protobuf:"bytes,2,opt,name=key_uri,json=keyUri,proto3" json:"key_uri,omitempty"`
	// OPTIONAL: Standard Additional Authenticated Data (AAD) byte buffer.
	Aad []byte `protobuf:"bytes,3,opt,name=aad,proto3,oneof" json:"aad,omitempty"`
	// OPTIONAL (Map): Key-Value Encryption Context.
	EncryptionContext map[string]string `protobuf:"bytes,4,rep,name=encryption_context,json=encryptionContext,proto3" json:"encryption_context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// OPTIONAL: The explicit cryptographic unwrapping mechanism.
	Mechanism *string `protobuf:"bytes,5,opt,name=mechanism,proto3,oneof" json:"mechanism,omitempty"`
	// OPTIONAL: Initialization Vector (IV) or Nonce.
	// Must be provided if it was returned in the WrapResponse.
	Iv []byte `protobuf:"bytes,6,opt,name=iv,proto3,oneof" json:"iv,omitempty"`
	// OPTIONAL (Map): Dynamic Configuration Pass-through.
	Options       map[string]string `protobuf:"bytes,7,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnwrapRequest) Reset() {
	*x = UnwrapRequest{}
	mi := &file_plugin_cipher_wrapper_v1_cipher_wrapper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnwrapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnwrapRequest) ProtoMessage() {}

func (x *UnwrapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_cipher_wrapper_v1_cipher_wrapper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnwrapRequest.ProtoReflect.Descriptor instead.
func (*UnwrapRequest) Descriptor() ([]byte, []int) {
	return file_plugin_cipher_wrapper_v1_cipher_wrapper_proto_rawDescGZIP(), []int{2}
}

func (x *UnwrapRequest) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

func (x *UnwrapRequest) GetKeyUri() string {
	if x != nil {
		return x.KeyUri
	}
	return ""
}

func (x *UnwrapRequest) GetAad() []byte {
	if x != nil {
		return x.Aad
	}
	return nil
}

func (x *UnwrapRequest) GetEncryptionContext() map[string]string {
	if x != nil {
		return x.EncryptionContext
	}
	return nil
}

func (x *UnwrapRequest) GetMechanism() string {
	if x != nil && x.Mechanism != nil {
		return *x.Mechanism
	}
	return ""
}

func (x *UnwrapRequest) GetIv() []byte {
	if x != nil {
		return x.Iv
	}
	return nil
}

func (x *UnwrapRequest) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

// UnwrapResponse returns the recovered raw cryptographic material.
type UnwrapResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// REQUIRED: The recovered raw cryptographic material.
	Plaintext []byte `protobuf:"bytes,1,opt,name=plaintext,proto3" json:"plaintext,omitempty"`
	// OPTIONAL (Map): Vendor-specific metadata.
	Metadata      map[string]string `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnwrapResponse) Reset() {
	*x = UnwrapResponse{}
	mi := &file_plugin_cipher_wrapper_v1_cipher_wrapper_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnwrapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnwrapResponse) ProtoMessage() {}

func (x *UnwrapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_cipher_wrapper_v1_cipher_wrapper_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnwrapResponse.ProtoReflect.Descriptor instead.
func (*UnwrapResponse) Descriptor() ([]byte, []int) {
	return file_plugin_cipher_wrapper_v1_cipher_wrapper_proto_rawDescGZIP(), []int{3}
}

func (x *UnwrapResponse) GetPlaintext() []byte {
	if x != nil {
		return x.Plaintext
	}
	return nil
}

func (x *UnwrapResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_plugin_cipher_wrapper_v1_cipher_wrapper_proto protoreflect.FileDescriptor

const file_plugin_cipher_wrapper_v1_cipher_wrapper_proto_rawDesc = "" +
	"\n" +
	"-plugin/cipher_wrapper/v1/cipher_wrapper.proto\x12\x18plugin.cipher_wrapper.v1\"\xed\x03\n" +
	"\vWrapRequest\x12\x1c\n" +
	"\tplaintext\x18\x01 \x01(\fR\tplaintext\x12\x17\n" +
	"\akey_uri\x18\x02 \x01(\tR\x06keyUri\x12\x15\n" +
	"\x03aad\x18\x03 \x01(\fH\x00R\x03aad\x88\x01\x01\x12k\n" +
	"\x12encryption_context\x18\x04 \x03(\v2<.plugin.cipher_wrapper.v1.WrapRequest.EncryptionContextEntryR\x11encryptionContext\x12!\n" +
	"\tmechanism\x18\x05 \x01(\tH\x01R\tmechanism\x88\x01\x01\x12\x13\n" +
	"\x02iv\x18\x06 \x01(\fH\x02R\x02iv\x88\x01\x01\x12L\n" +
	"\aoptions\x18\a \x03(\v22.plugin.cipher_wrapper.v1.WrapRequest.OptionsEntryR\aoptions\x1aD\n" +
	"\x16EncryptionContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x06\n" +
	"\x04_aadB\f\n" +
	"\n" +
	"_mechanismB\x05\n" +
	"\x03_iv\"\x97\x02\n" +
	"\fWrapResponse\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x01 \x01(\fR\n" +
	"ciphertext\x12)\n" +
	"\x0ekey_version_id\x18\x02 \x01(\tH\x00R\fkeyVersionId\x88\x01\x01\x12\x13\n" +
	"\x02iv\x18\x03 \x01(\fH\x01R\x02iv\x88\x01\x01\x12P\n" +
	"\bmetadata\x18\x04 \x03(\v24.plugin.cipher_wrapper.v1.WrapResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x11\n" +
	"\x0f_key_version_idB\x05\n" +
	"\x03_iv\"\xf5\x03\n" +
	"\rUnwrapRequest\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x01 \x01(\fR\n" +
	"ciphertext\x12\x17\n" +
	"\akey_uri\x18\x02 \x01(\tR\x06keyUri\x12\x15\n" +
	"\x03aad\x18\x03 \x01(\fH\x00R\x03aad\x88\x01\x01\x12m\n" +
	"\x12encryption_context\x18\x04 \x03(\v2>.plugin.cipher_wrapper.v1.UnwrapRequest.EncryptionContextEntryR\x11encryptionContext\x12!\n" +
	"\tmechanism\x18\x05 \x01(\tH\x01R\tmechanism\x88\x01\x01\x12\x13\n" +
	"\x02iv\x18\x06 \x01(\fH\x02R\x02iv\x88\x01\x01\x12N\n" +
	"\aoptions\x18\a \x03(\v24.plugin.cipher_wrapper.v1.UnwrapRequest.OptionsEntryR\aoptions\x1aD\n" +
	"\x16EncryptionContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x06\n" +
	"\x04_aadB\f\n" +
	"\n" +
	"_mechanismB\x05\n" +
	"\x03_iv\"\xbf\x01\n" +
	"\x0eUnwrapResponse\x12\x1c\n" +
	"\tplaintext\x18\x01 \x01(\fR\tplaintext\x12R\n" +
	"\bmetadata\x18\x02 \x03(\v26.plugin.cipher_wrapper.v1.UnwrapResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xc3\x01\n" +
	"\rCipherWrapper\x12U\n" +
	"\x04Wrap\x12%.plugin.cipher_wrapper.v1.WrapRequest\x1a&.plugin.cipher_wrapper.v1.WrapResponse\x12[\n" +
	"\x06Unwrap\x12'.plugin.cipher_wrapper.v1.UnwrapRequest\x1a(.plugin.cipher_wrapper.v1.UnwrapResponseB\xff\x01\n" +
	"\x1ccom.plugin.cipher_wrapper.v1B\x12CipherWrapperProtoP\x01ZMgithub.com/openkcm/plugin-sdk/proto/plugin/cipher_wrapper/v1;cipher_wrapperv1\xa2\x02\x03PCX\xaa\x02\x17Plugin.CipherWrapper.V1\xca\x02\x17Plugin\\CipherWrapper\\V1\xe2\x02#Plugin\\CipherWrapper\\V1\\GPBMetadata\xea\x02\x19Plugin::CipherWrapper::V1b\x06proto3"

var (
	file_plugin_cipher_wrapper_v1_cipher_wrapper_proto_rawDescOnce sync.Once
	file_plugin_cipher_wrapper_v1_cipher_wrapper_proto_rawDescData []byte
)

func file_plugin_cipher_wrapper_v1_cipher_wrapper_proto_rawDescGZIP() []byte {
	file_plugin_cipher_wrapper_v1_cipher_wrapper_proto_rawDescOnce.Do(func() {
		file_plugin_cipher_wrapper_v1_cipher_wrapper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_cipher_wrapper_v1_cipher_wrapper_proto_rawDesc), len(file_plugin_cipher_wrapper_v1_cipher_wrapper_proto_rawDesc)))
	})
	return file_plugin_cipher_wrapper_v1_cipher_wrapper_proto_rawDescData
}

var file_plugin_cipher_wrapper_v1_cipher_wrapper_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_plugin_cipher_wrapper_v1_cipher_wrapper_proto_goTypes = []any{
	(*WrapRequest)(nil),    // 0: plugin.cipher_wrapper.v1.WrapRequest
	(*WrapResponse)(nil),   // 1: plugin.cipher_wrapper.v1.WrapResponse
	(*UnwrapRequest)(nil),  // 2: plugin.cipher_wrapper.v1.UnwrapRequest
	(*UnwrapResponse)(nil), // 3: plugin.cipher_wrapper.v1.UnwrapResponse
	nil,                    // 4: plugin.cipher_wrapper.v1.WrapRequest.EncryptionContextEntry
	nil,                    // 5: plugin.cipher_wrapper.v1.WrapRequest.OptionsEntry
	nil,                    // 6: plugin.cipher_wrapper.v1.WrapResponse.MetadataEntry
	nil,                    // 7: plugin.cipher_wrapper.v1.UnwrapRequest.EncryptionContextEntry
	nil,                    // 8: plugin.cipher_wrapper.v1.UnwrapRequest.OptionsEntry
	nil,                    // 9: plugin.cipher_wrapper.v1.UnwrapResponse.MetadataEntry
}
var file_plugin_cipher_wrapper_v1_cipher_wrapper_proto_depIdxs = []int32{
	4, // 0: plugin.cipher_wrapper.v1.WrapRequest.encryption_context:type_name -> plugin.cipher_wrapper.v1.WrapRequest.EncryptionContextEntry
	5, // 1: plugin.cipher_wrapper.v1.WrapRequest.options:type_name -> plugin.cipher_wrapper.v1.WrapRequest.OptionsEntry
	6, // 2: plugin.cipher_wrapper.v1.WrapResponse.metadata:type_name -> plugin.cipher_wrapper.v1.WrapResponse.MetadataEntry
	7, // 3: plugin.cipher_wrapper.v1.UnwrapRequest.encryption_context:type_name -> plugin.cipher_wrapper.v1.UnwrapRequest.EncryptionContextEntry
	8, // 4: plugin.cipher_wrapper.v1.UnwrapRequest.options:type_name -> plugin.cipher_wrapper.v1.UnwrapRequest.OptionsEntry
	9, // 5: plugin.cipher_wrapper.v1.UnwrapResponse.metadata:type_name -> plugin.cipher_wrapper.v1.UnwrapResponse.MetadataEntry
	0, // 6: plugin.cipher_wrapper.v1.CipherWrapper.Wrap:input_type -> plugin.cipher_wrapper.v1.WrapRequest
	2, // 7: plugin.cipher_wrapper.v1.CipherWrapper.Unwrap:input_type -> plugin.cipher_wrapper.v1.UnwrapRequest
	1, // 8: plugin.cipher_wrapper.v1.CipherWrapper.Wrap:output_type -> plugin.cipher_wrapper.v1.WrapResponse
	3, // 9: plugin.cipher_wrapper.v1.CipherWrapper.Unwrap:output_type -> plugin.cipher_wrapper.v1.UnwrapResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_plugin_cipher_wrapper_v1_cipher_wrapper_proto_init() }
func file_plugin_cipher_wrapper_v1_cipher_wrapper_proto_init() {
	if File_plugin_cipher_wrapper_v1_cipher_wrapper_proto != nil {
		return
	}
	file_plugin_cipher_wrapper_v1_cipher_wrapper_proto_msgTypes[0].OneofWrappers = []any{}
	file_plugin_cipher_wrapper_v1_cipher_wrapper_proto_msgTypes[1].OneofWrappers = []any{}
	file_plugin_cipher_wrapper_v1_cipher_wrapper_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_cipher_wrapper_v1_cipher_wrapper_proto_rawDesc), len(file_plugin_cipher_wrapper_v1_cipher_wrapper_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugin_cipher_wrapper_v1_cipher_wrapper_proto_goTypes,
		DependencyIndexes: file_plugin_cipher_wrapper_v1_cipher_wrapper_proto_depIdxs,
		MessageInfos:      file_plugin_cipher_wrapper_v1_cipher_wrapper_proto_msgTypes,
	}.Build()
	File_plugin_cipher_wrapper_v1_cipher_wrapper_proto = out.File
	file_plugin_cipher_wrapper_v1_cipher_wrapper_proto_goTypes = nil
	file_plugin_cipher_wrapper_v1_cipher_wrapper_proto_depIdxs = nil
}
