// Code generated by protoc-gen-go-extension. DO NOT EDIT.

package cipher_wrapperv1

import (
	grpc "google.golang.org/grpc"

	api "github.com/openkcm/plugin-sdk/api"
)

const (
	Type                = "CipherWrapper"
	GRPCServiceFullName = "plugin.cipher_wrapper.v1.CipherWrapper"
)

func CipherWrapperPluginServer(server CipherWrapperServer) api.PluginServer {
	return cipherWrapperPluginServer{CipherWrapperServer: server}
}

type cipherWrapperPluginServer struct {
	CipherWrapperServer
}

func (s cipherWrapperPluginServer) Type() string {
	return Type
}

func (s cipherWrapperPluginServer) GRPCServiceName() string {
	return GRPCServiceFullName
}

func (s cipherWrapperPluginServer) RegisterServer(server *grpc.Server) any {
	RegisterCipherWrapperServer(server, s.CipherWrapperServer)
	return s.CipherWrapperServer
}

type CipherWrapperPluginClient struct {
	CipherWrapperClient
}

func (s CipherWrapperPluginClient) Type() string {
	return Type
}

func (c *CipherWrapperPluginClient) IsInitialized() bool {
	return c.CipherWrapperClient != nil
}

func (c *CipherWrapperPluginClient) GRPCServiceName() string {
	return GRPCServiceFullName
}

func (c *CipherWrapperPluginClient) InitClient(conn grpc.ClientConnInterface) any {
	c.CipherWrapperClient = NewCipherWrapperClient(conn)
	return c.CipherWrapperClient
}
