// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: plugin/keystore/management/v1/management.proto

package managementv1

import (
	v1 "github.com/openkcm/plugin-sdk/proto/plugin/keystore/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SupportedRegion represents a region where the keystore can be created or accessed.
type SupportedRegion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TechnicalName string                 `protobuf:"bytes,2,opt,name=technical_name,json=technicalName,proto3" json:"technical_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SupportedRegion) Reset() {
	*x = SupportedRegion{}
	mi := &file_plugin_keystore_management_v1_management_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SupportedRegion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupportedRegion) ProtoMessage() {}

func (x *SupportedRegion) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_keystore_management_v1_management_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupportedRegion.ProtoReflect.Descriptor instead.
func (*SupportedRegion) Descriptor() ([]byte, []int) {
	return file_plugin_keystore_management_v1_management_proto_rawDescGZIP(), []int{0}
}

func (x *SupportedRegion) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SupportedRegion) GetTechnicalName() string {
	if x != nil {
		return x.TechnicalName
	}
	return ""
}

// ManagementConfig represents the configuration details for the management role of a keystore instance.
type ManagementConfig struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	LocalityId    string                     `protobuf:"bytes,1,opt,name=locality_id,json=localityId,proto3" json:"locality_id,omitempty"`
	CommonName    string                     `protobuf:"bytes,2,opt,name=common_name,json=commonName,proto3" json:"common_name,omitempty"`
	AccessData    *v1.KeystoreInstanceConfig `protobuf:"bytes,3,opt,name=access_data,json=accessData,proto3" json:"access_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManagementConfig) Reset() {
	*x = ManagementConfig{}
	mi := &file_plugin_keystore_management_v1_management_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagementConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagementConfig) ProtoMessage() {}

func (x *ManagementConfig) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_keystore_management_v1_management_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagementConfig.ProtoReflect.Descriptor instead.
func (*ManagementConfig) Descriptor() ([]byte, []int) {
	return file_plugin_keystore_management_v1_management_proto_rawDescGZIP(), []int{1}
}

func (x *ManagementConfig) GetLocalityId() string {
	if x != nil {
		return x.LocalityId
	}
	return ""
}

func (x *ManagementConfig) GetCommonName() string {
	if x != nil {
		return x.CommonName
	}
	return ""
}

func (x *ManagementConfig) GetAccessData() *v1.KeystoreInstanceConfig {
	if x != nil {
		return x.AccessData
	}
	return nil
}

// CreateKeystoreRequest represents the request to create a new keystore instance.
// The values field contains the necessary parameters for creating the keystore,
// which can vary depending on the implementation and requirements of the keystore provider.
type CreateKeystoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        *structpb.Struct       `protobuf:"bytes,1,opt,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateKeystoreRequest) Reset() {
	*x = CreateKeystoreRequest{}
	mi := &file_plugin_keystore_management_v1_management_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateKeystoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKeystoreRequest) ProtoMessage() {}

func (x *CreateKeystoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_keystore_management_v1_management_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKeystoreRequest.ProtoReflect.Descriptor instead.
func (*CreateKeystoreRequest) Descriptor() ([]byte, []int) {
	return file_plugin_keystore_management_v1_management_proto_rawDescGZIP(), []int{2}
}

func (x *CreateKeystoreRequest) GetValues() *structpb.Struct {
	if x != nil {
		return x.Values
	}
	return nil
}

// CreateKeystoreResponse represents the response after creating a new keystore instance.
// - The config field (deprecated) contains the configuration details of the created keystore instance,
// including fields: locality_id, common_name, management_access_data, and supported_regions.
type CreateKeystoreResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Deprecated: Marked as deprecated in plugin/keystore/management/v1/management.proto.
	Config               *v1.KeystoreInstanceConfig `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	RoleManagementConfig *ManagementConfig          `protobuf:"bytes,2,opt,name=role_management_config,json=roleManagementConfig,proto3" json:"role_management_config,omitempty"`
	KeyManagementConfig  *ManagementConfig          `protobuf:"bytes,3,opt,name=key_management_config,json=keyManagementConfig,proto3" json:"key_management_config,omitempty"`
	SupportedRegions     []*SupportedRegion         `protobuf:"bytes,4,rep,name=supported_regions,json=supportedRegions,proto3" json:"supported_regions,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CreateKeystoreResponse) Reset() {
	*x = CreateKeystoreResponse{}
	mi := &file_plugin_keystore_management_v1_management_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateKeystoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKeystoreResponse) ProtoMessage() {}

func (x *CreateKeystoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_keystore_management_v1_management_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKeystoreResponse.ProtoReflect.Descriptor instead.
func (*CreateKeystoreResponse) Descriptor() ([]byte, []int) {
	return file_plugin_keystore_management_v1_management_proto_rawDescGZIP(), []int{3}
}

// Deprecated: Marked as deprecated in plugin/keystore/management/v1/management.proto.
func (x *CreateKeystoreResponse) GetConfig() *v1.KeystoreInstanceConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *CreateKeystoreResponse) GetRoleManagementConfig() *ManagementConfig {
	if x != nil {
		return x.RoleManagementConfig
	}
	return nil
}

func (x *CreateKeystoreResponse) GetKeyManagementConfig() *ManagementConfig {
	if x != nil {
		return x.KeyManagementConfig
	}
	return nil
}

func (x *CreateKeystoreResponse) GetSupportedRegions() []*SupportedRegion {
	if x != nil {
		return x.SupportedRegions
	}
	return nil
}

type DeleteKeystoreRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Config        *v1.KeystoreInstanceConfig `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteKeystoreRequest) Reset() {
	*x = DeleteKeystoreRequest{}
	mi := &file_plugin_keystore_management_v1_management_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteKeystoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKeystoreRequest) ProtoMessage() {}

func (x *DeleteKeystoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_keystore_management_v1_management_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKeystoreRequest.ProtoReflect.Descriptor instead.
func (*DeleteKeystoreRequest) Descriptor() ([]byte, []int) {
	return file_plugin_keystore_management_v1_management_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteKeystoreRequest) GetConfig() *v1.KeystoreInstanceConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type DeleteKeystoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteKeystoreResponse) Reset() {
	*x = DeleteKeystoreResponse{}
	mi := &file_plugin_keystore_management_v1_management_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteKeystoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKeystoreResponse) ProtoMessage() {}

func (x *DeleteKeystoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_keystore_management_v1_management_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKeystoreResponse.ProtoReflect.Descriptor instead.
func (*DeleteKeystoreResponse) Descriptor() ([]byte, []int) {
	return file_plugin_keystore_management_v1_management_proto_rawDescGZIP(), []int{5}
}

// GrantTrustRequest represents the request to grant trust to a client certificate subject pattern
// for accessing a keystore instance from the crypto layer.
// - The config field contains the authentication configuration of the role management role for the keystore instance,
// which is used to authenticate the request to grant trust.
// - The subject field contains the client certificate subject to grant trust to
// - The region field specifies the logical region for which the trust is being granted
type GrantTrustRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Config        *v1.KeystoreInstanceConfig `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	Subject       string                     `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Region        string                     `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrantTrustRequest) Reset() {
	*x = GrantTrustRequest{}
	mi := &file_plugin_keystore_management_v1_management_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantTrustRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantTrustRequest) ProtoMessage() {}

func (x *GrantTrustRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_keystore_management_v1_management_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantTrustRequest.ProtoReflect.Descriptor instead.
func (*GrantTrustRequest) Descriptor() ([]byte, []int) {
	return file_plugin_keystore_management_v1_management_proto_rawDescGZIP(), []int{6}
}

func (x *GrantTrustRequest) GetConfig() *v1.KeystoreInstanceConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *GrantTrustRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *GrantTrustRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

// GrantTrustResponse represents the response after granting trust to a client certificate subject pattern
// for accessing a keystore instance. Returns the access data of the configured trust
type GrantTrustResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessData    *structpb.Struct       `protobuf:"bytes,1,opt,name=access_data,json=accessData,proto3" json:"access_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrantTrustResponse) Reset() {
	*x = GrantTrustResponse{}
	mi := &file_plugin_keystore_management_v1_management_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantTrustResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantTrustResponse) ProtoMessage() {}

func (x *GrantTrustResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_keystore_management_v1_management_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantTrustResponse.ProtoReflect.Descriptor instead.
func (*GrantTrustResponse) Descriptor() ([]byte, []int) {
	return file_plugin_keystore_management_v1_management_proto_rawDescGZIP(), []int{7}
}

func (x *GrantTrustResponse) GetAccessData() *structpb.Struct {
	if x != nil {
		return x.AccessData
	}
	return nil
}

// RemoveTrustRequest represents the request to remove trust for a client certificate subject pattern
// to revoke access to a keystore instance.
// - The config field contains the authentication configuration of the role management role for the keystore instance,
// which is used to authenticate the request to remove trust.
// - The access_data field contains the access data of the trust to be removed
type RemoveTrustRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Config        *v1.KeystoreInstanceConfig `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	AccessData    *structpb.Struct           `protobuf:"bytes,2,opt,name=access_data,json=accessData,proto3" json:"access_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveTrustRequest) Reset() {
	*x = RemoveTrustRequest{}
	mi := &file_plugin_keystore_management_v1_management_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveTrustRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveTrustRequest) ProtoMessage() {}

func (x *RemoveTrustRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_keystore_management_v1_management_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveTrustRequest.ProtoReflect.Descriptor instead.
func (*RemoveTrustRequest) Descriptor() ([]byte, []int) {
	return file_plugin_keystore_management_v1_management_proto_rawDescGZIP(), []int{8}
}

func (x *RemoveTrustRequest) GetConfig() *v1.KeystoreInstanceConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *RemoveTrustRequest) GetAccessData() *structpb.Struct {
	if x != nil {
		return x.AccessData
	}
	return nil
}

type RemoveTrustResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveTrustResponse) Reset() {
	*x = RemoveTrustResponse{}
	mi := &file_plugin_keystore_management_v1_management_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveTrustResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveTrustResponse) ProtoMessage() {}

func (x *RemoveTrustResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_keystore_management_v1_management_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveTrustResponse.ProtoReflect.Descriptor instead.
func (*RemoveTrustResponse) Descriptor() ([]byte, []int) {
	return file_plugin_keystore_management_v1_management_proto_rawDescGZIP(), []int{9}
}

var File_plugin_keystore_management_v1_management_proto protoreflect.FileDescriptor

const file_plugin_keystore_management_v1_management_proto_rawDesc = "" +
	"\n" +
	".plugin/keystore/management/v1/management.proto\x12\x1dplugin.keystore.management.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a&plugin/keystore/common/v1/common.proto\"L\n" +
	"\x0fSupportedRegion\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\x0etechnical_name\x18\x02 \x01(\tR\rtechnicalName\"\xa8\x01\n" +
	"\x10ManagementConfig\x12\x1f\n" +
	"\vlocality_id\x18\x01 \x01(\tR\n" +
	"localityId\x12\x1f\n" +
	"\vcommon_name\x18\x02 \x01(\tR\n" +
	"commonName\x12R\n" +
	"\vaccess_data\x18\x03 \x01(\v21.plugin.keystore.common.v1.KeystoreInstanceConfigR\n" +
	"accessData\"H\n" +
	"\x15CreateKeystoreRequest\x12/\n" +
	"\x06values\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x06values\"\x90\x03\n" +
	"\x16CreateKeystoreResponse\x12M\n" +
	"\x06config\x18\x01 \x01(\v21.plugin.keystore.common.v1.KeystoreInstanceConfigB\x02\x18\x01R\x06config\x12e\n" +
	"\x16role_management_config\x18\x02 \x01(\v2/.plugin.keystore.management.v1.ManagementConfigR\x14roleManagementConfig\x12c\n" +
	"\x15key_management_config\x18\x03 \x01(\v2/.plugin.keystore.management.v1.ManagementConfigR\x13keyManagementConfig\x12[\n" +
	"\x11supported_regions\x18\x04 \x03(\v2..plugin.keystore.management.v1.SupportedRegionR\x10supportedRegions\"b\n" +
	"\x15DeleteKeystoreRequest\x12I\n" +
	"\x06config\x18\x01 \x01(\v21.plugin.keystore.common.v1.KeystoreInstanceConfigR\x06config\"\x18\n" +
	"\x16DeleteKeystoreResponse\"\x90\x01\n" +
	"\x11GrantTrustRequest\x12I\n" +
	"\x06config\x18\x01 \x01(\v21.plugin.keystore.common.v1.KeystoreInstanceConfigR\x06config\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x16\n" +
	"\x06region\x18\x03 \x01(\tR\x06region\"N\n" +
	"\x12GrantTrustResponse\x128\n" +
	"\vaccess_data\x18\x01 \x01(\v2\x17.google.protobuf.StructR\n" +
	"accessData\"\x99\x01\n" +
	"\x12RemoveTrustRequest\x12I\n" +
	"\x06config\x18\x01 \x01(\v21.plugin.keystore.common.v1.KeystoreInstanceConfigR\x06config\x128\n" +
	"\vaccess_data\x18\x02 \x01(\v2\x17.google.protobuf.StructR\n" +
	"accessData\"\x15\n" +
	"\x13RemoveTrustResponse2\xf9\x03\n" +
	"\x10KeystoreProvider\x12}\n" +
	"\x0eCreateKeystore\x124.plugin.keystore.management.v1.CreateKeystoreRequest\x1a5.plugin.keystore.management.v1.CreateKeystoreResponse\x12}\n" +
	"\x0eDeleteKeystore\x124.plugin.keystore.management.v1.DeleteKeystoreRequest\x1a5.plugin.keystore.management.v1.DeleteKeystoreResponse\x12q\n" +
	"\n" +
	"GrantTrust\x120.plugin.keystore.management.v1.GrantTrustRequest\x1a1.plugin.keystore.management.v1.GrantTrustResponse\x12t\n" +
	"\vRemoveTrust\x121.plugin.keystore.management.v1.RemoveTrustRequest\x1a2.plugin.keystore.management.v1.RemoveTrustResponseBPZNgithub.com/openkcm/plugin-sdk/proto/plugin/keystore/management/v1;managementv1b\x06proto3"

var (
	file_plugin_keystore_management_v1_management_proto_rawDescOnce sync.Once
	file_plugin_keystore_management_v1_management_proto_rawDescData []byte
)

func file_plugin_keystore_management_v1_management_proto_rawDescGZIP() []byte {
	file_plugin_keystore_management_v1_management_proto_rawDescOnce.Do(func() {
		file_plugin_keystore_management_v1_management_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_keystore_management_v1_management_proto_rawDesc), len(file_plugin_keystore_management_v1_management_proto_rawDesc)))
	})
	return file_plugin_keystore_management_v1_management_proto_rawDescData
}

var file_plugin_keystore_management_v1_management_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_plugin_keystore_management_v1_management_proto_goTypes = []any{
	(*SupportedRegion)(nil),           // 0: plugin.keystore.management.v1.SupportedRegion
	(*ManagementConfig)(nil),          // 1: plugin.keystore.management.v1.ManagementConfig
	(*CreateKeystoreRequest)(nil),     // 2: plugin.keystore.management.v1.CreateKeystoreRequest
	(*CreateKeystoreResponse)(nil),    // 3: plugin.keystore.management.v1.CreateKeystoreResponse
	(*DeleteKeystoreRequest)(nil),     // 4: plugin.keystore.management.v1.DeleteKeystoreRequest
	(*DeleteKeystoreResponse)(nil),    // 5: plugin.keystore.management.v1.DeleteKeystoreResponse
	(*GrantTrustRequest)(nil),         // 6: plugin.keystore.management.v1.GrantTrustRequest
	(*GrantTrustResponse)(nil),        // 7: plugin.keystore.management.v1.GrantTrustResponse
	(*RemoveTrustRequest)(nil),        // 8: plugin.keystore.management.v1.RemoveTrustRequest
	(*RemoveTrustResponse)(nil),       // 9: plugin.keystore.management.v1.RemoveTrustResponse
	(*v1.KeystoreInstanceConfig)(nil), // 10: plugin.keystore.common.v1.KeystoreInstanceConfig
	(*structpb.Struct)(nil),           // 11: google.protobuf.Struct
}
var file_plugin_keystore_management_v1_management_proto_depIdxs = []int32{
	10, // 0: plugin.keystore.management.v1.ManagementConfig.access_data:type_name -> plugin.keystore.common.v1.KeystoreInstanceConfig
	11, // 1: plugin.keystore.management.v1.CreateKeystoreRequest.values:type_name -> google.protobuf.Struct
	10, // 2: plugin.keystore.management.v1.CreateKeystoreResponse.config:type_name -> plugin.keystore.common.v1.KeystoreInstanceConfig
	1,  // 3: plugin.keystore.management.v1.CreateKeystoreResponse.role_management_config:type_name -> plugin.keystore.management.v1.ManagementConfig
	1,  // 4: plugin.keystore.management.v1.CreateKeystoreResponse.key_management_config:type_name -> plugin.keystore.management.v1.ManagementConfig
	0,  // 5: plugin.keystore.management.v1.CreateKeystoreResponse.supported_regions:type_name -> plugin.keystore.management.v1.SupportedRegion
	10, // 6: plugin.keystore.management.v1.DeleteKeystoreRequest.config:type_name -> plugin.keystore.common.v1.KeystoreInstanceConfig
	10, // 7: plugin.keystore.management.v1.GrantTrustRequest.config:type_name -> plugin.keystore.common.v1.KeystoreInstanceConfig
	11, // 8: plugin.keystore.management.v1.GrantTrustResponse.access_data:type_name -> google.protobuf.Struct
	10, // 9: plugin.keystore.management.v1.RemoveTrustRequest.config:type_name -> plugin.keystore.common.v1.KeystoreInstanceConfig
	11, // 10: plugin.keystore.management.v1.RemoveTrustRequest.access_data:type_name -> google.protobuf.Struct
	2,  // 11: plugin.keystore.management.v1.KeystoreProvider.CreateKeystore:input_type -> plugin.keystore.management.v1.CreateKeystoreRequest
	4,  // 12: plugin.keystore.management.v1.KeystoreProvider.DeleteKeystore:input_type -> plugin.keystore.management.v1.DeleteKeystoreRequest
	6,  // 13: plugin.keystore.management.v1.KeystoreProvider.GrantTrust:input_type -> plugin.keystore.management.v1.GrantTrustRequest
	8,  // 14: plugin.keystore.management.v1.KeystoreProvider.RemoveTrust:input_type -> plugin.keystore.management.v1.RemoveTrustRequest
	3,  // 15: plugin.keystore.management.v1.KeystoreProvider.CreateKeystore:output_type -> plugin.keystore.management.v1.CreateKeystoreResponse
	5,  // 16: plugin.keystore.management.v1.KeystoreProvider.DeleteKeystore:output_type -> plugin.keystore.management.v1.DeleteKeystoreResponse
	7,  // 17: plugin.keystore.management.v1.KeystoreProvider.GrantTrust:output_type -> plugin.keystore.management.v1.GrantTrustResponse
	9,  // 18: plugin.keystore.management.v1.KeystoreProvider.RemoveTrust:output_type -> plugin.keystore.management.v1.RemoveTrustResponse
	15, // [15:19] is the sub-list for method output_type
	11, // [11:15] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_plugin_keystore_management_v1_management_proto_init() }
func file_plugin_keystore_management_v1_management_proto_init() {
	if File_plugin_keystore_management_v1_management_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_keystore_management_v1_management_proto_rawDesc), len(file_plugin_keystore_management_v1_management_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugin_keystore_management_v1_management_proto_goTypes,
		DependencyIndexes: file_plugin_keystore_management_v1_management_proto_depIdxs,
		MessageInfos:      file_plugin_keystore_management_v1_management_proto_msgTypes,
	}.Build()
	File_plugin_keystore_management_v1_management_proto = out.File
	file_plugin_keystore_management_v1_management_proto_goTypes = nil
	file_plugin_keystore_management_v1_management_proto_depIdxs = nil
}
