// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: plugin/keystore/management/v1/management.proto

package managementv1

import (
	v1 "github.com/openkcm/plugin-sdk/proto/plugin/keystore/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KeystoreCreationStatus int32

const (
	// Default value when status field is not set (for backwards compatibility)
	KeystoreCreationStatus_KEYSTORE_CREATION_STATUS_UNSPECIFIED KeystoreCreationStatus = 0
	// Keystore is fully configured and ready to use
	KeystoreCreationStatus_KEYSTORE_CREATION_STATUS_ACTIVE KeystoreCreationStatus = 1
	// Account created, waiting for activation
	KeystoreCreationStatus_KEYSTORE_CREATION_STATUS_PENDING_ACTIVATION KeystoreCreationStatus = 2
	// Keystore creation failed permanently
	KeystoreCreationStatus_KEYSTORE_CREATION_STATUS_FAILED KeystoreCreationStatus = 3
)

// Enum value maps for KeystoreCreationStatus.
var (
	KeystoreCreationStatus_name = map[int32]string{
		0: "KEYSTORE_CREATION_STATUS_UNSPECIFIED",
		1: "KEYSTORE_CREATION_STATUS_ACTIVE",
		2: "KEYSTORE_CREATION_STATUS_PENDING_ACTIVATION",
		3: "KEYSTORE_CREATION_STATUS_FAILED",
	}
	KeystoreCreationStatus_value = map[string]int32{
		"KEYSTORE_CREATION_STATUS_UNSPECIFIED":        0,
		"KEYSTORE_CREATION_STATUS_ACTIVE":             1,
		"KEYSTORE_CREATION_STATUS_PENDING_ACTIVATION": 2,
		"KEYSTORE_CREATION_STATUS_FAILED":             3,
	}
)

func (x KeystoreCreationStatus) Enum() *KeystoreCreationStatus {
	p := new(KeystoreCreationStatus)
	*p = x
	return p
}

func (x KeystoreCreationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KeystoreCreationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_keystore_management_v1_management_proto_enumTypes[0].Descriptor()
}

func (KeystoreCreationStatus) Type() protoreflect.EnumType {
	return &file_plugin_keystore_management_v1_management_proto_enumTypes[0]
}

func (x KeystoreCreationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KeystoreCreationStatus.Descriptor instead.
func (KeystoreCreationStatus) EnumDescriptor() ([]byte, []int) {
	return file_plugin_keystore_management_v1_management_proto_rawDescGZIP(), []int{0}
}

// TrustType specifies whether a management or crypto role should be created.
type TrustType int32

const (
	TrustType_TRUST_TYPE_UNSPECIFIED TrustType = 0
	TrustType_TRUST_TYPE_MANAGEMENT  TrustType = 1
	TrustType_TRUST_TYPE_CRYPTO      TrustType = 2
)

// Enum value maps for TrustType.
var (
	TrustType_name = map[int32]string{
		0: "TRUST_TYPE_UNSPECIFIED",
		1: "TRUST_TYPE_MANAGEMENT",
		2: "TRUST_TYPE_CRYPTO",
	}
	TrustType_value = map[string]int32{
		"TRUST_TYPE_UNSPECIFIED": 0,
		"TRUST_TYPE_MANAGEMENT":  1,
		"TRUST_TYPE_CRYPTO":      2,
	}
)

func (x TrustType) Enum() *TrustType {
	p := new(TrustType)
	*p = x
	return p
}

func (x TrustType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TrustType) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_keystore_management_v1_management_proto_enumTypes[1].Descriptor()
}

func (TrustType) Type() protoreflect.EnumType {
	return &file_plugin_keystore_management_v1_management_proto_enumTypes[1]
}

func (x TrustType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TrustType.Descriptor instead.
func (TrustType) EnumDescriptor() ([]byte, []int) {
	return file_plugin_keystore_management_v1_management_proto_rawDescGZIP(), []int{1}
}

// SupportedRegion represents a region where the keystore can be created or accessed.
type SupportedRegion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TechnicalName string                 `protobuf:"bytes,2,opt,name=technical_name,json=technicalName,proto3" json:"technical_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SupportedRegion) Reset() {
	*x = SupportedRegion{}
	mi := &file_plugin_keystore_management_v1_management_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SupportedRegion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupportedRegion) ProtoMessage() {}

func (x *SupportedRegion) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_keystore_management_v1_management_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupportedRegion.ProtoReflect.Descriptor instead.
func (*SupportedRegion) Descriptor() ([]byte, []int) {
	return file_plugin_keystore_management_v1_management_proto_rawDescGZIP(), []int{0}
}

func (x *SupportedRegion) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SupportedRegion) GetTechnicalName() string {
	if x != nil {
		return x.TechnicalName
	}
	return ""
}

// ManagementConfig represents the configuration details for the management role of a keystore instance.
type ManagementConfig struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	LocalityId    string                     `protobuf:"bytes,1,opt,name=locality_id,json=localityId,proto3" json:"locality_id,omitempty"`
	CommonName    string                     `protobuf:"bytes,2,opt,name=common_name,json=commonName,proto3" json:"common_name,omitempty"`
	AccessData    *v1.KeystoreInstanceConfig `protobuf:"bytes,3,opt,name=access_data,json=accessData,proto3" json:"access_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManagementConfig) Reset() {
	*x = ManagementConfig{}
	mi := &file_plugin_keystore_management_v1_management_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagementConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagementConfig) ProtoMessage() {}

func (x *ManagementConfig) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_keystore_management_v1_management_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagementConfig.ProtoReflect.Descriptor instead.
func (*ManagementConfig) Descriptor() ([]byte, []int) {
	return file_plugin_keystore_management_v1_management_proto_rawDescGZIP(), []int{1}
}

func (x *ManagementConfig) GetLocalityId() string {
	if x != nil {
		return x.LocalityId
	}
	return ""
}

func (x *ManagementConfig) GetCommonName() string {
	if x != nil {
		return x.CommonName
	}
	return ""
}

func (x *ManagementConfig) GetAccessData() *v1.KeystoreInstanceConfig {
	if x != nil {
		return x.AccessData
	}
	return nil
}

// CreateKeystoreRequest represents the request to create a new keystore instance.
// The values field contains the necessary parameters for creating the keystore,
// which can vary depending on the implementation and requirements of the keystore provider.
type CreateKeystoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        *structpb.Struct       `protobuf:"bytes,1,opt,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateKeystoreRequest) Reset() {
	*x = CreateKeystoreRequest{}
	mi := &file_plugin_keystore_management_v1_management_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateKeystoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKeystoreRequest) ProtoMessage() {}

func (x *CreateKeystoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_keystore_management_v1_management_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKeystoreRequest.ProtoReflect.Descriptor instead.
func (*CreateKeystoreRequest) Descriptor() ([]byte, []int) {
	return file_plugin_keystore_management_v1_management_proto_rawDescGZIP(), []int{2}
}

func (x *CreateKeystoreRequest) GetValues() *structpb.Struct {
	if x != nil {
		return x.Values
	}
	return nil
}

// CreateKeystoreResponse represents the response after creating a new keystore instance.
// - The config field (deprecated) contains the configuration details of the created keystore instance,
// including fields: locality_id, common_name, management_access_data, and supported_regions.
type CreateKeystoreResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Deprecated: Marked as deprecated in plugin/keystore/management/v1/management.proto.
	Config               *v1.KeystoreInstanceConfig `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	RoleManagementConfig *ManagementConfig          `protobuf:"bytes,2,opt,name=role_management_config,json=roleManagementConfig,proto3" json:"role_management_config,omitempty"`
	KeyManagementConfig  *ManagementConfig          `protobuf:"bytes,3,opt,name=key_management_config,json=keyManagementConfig,proto3" json:"key_management_config,omitempty"`
	SupportedRegions     []*SupportedRegion         `protobuf:"bytes,4,rep,name=supported_regions,json=supportedRegions,proto3" json:"supported_regions,omitempty"`
	// Status of keystore creation
	// Values: "ACTIVE" (immediately ready), "PENDING_ACTIVATION" (account created, waiting for activation), "FAILED" (creation failed)
	// Optional field - when not set (absent), clients should treat the keystore as "ACTIVE" for backwards compatibility with old plugins
	// New plugins should explicitly set this field to indicate the actual status
	Status *KeystoreCreationStatus `protobuf:"varint,5,opt,name=status,proto3,enum=plugin.keystore.management.v1.KeystoreCreationStatus,oneof" json:"status,omitempty"`
	// Account ID for tracking pending keystores
	// Required when status is "PENDING_ACTIVATION"
	// Used to poll activation status via GetKeystoreStatus and finalize via FinalizeKeystoreSetup
	// The plugin maintains the mapping between this ID and the original CreateKeystore request parameters
	AccountId *string `protobuf:"bytes,6,opt,name=account_id,json=accountId,proto3,oneof" json:"account_id,omitempty"`
	// Error message when status is "FAILED"
	// Provides details about what went wrong during creation
	ErrorMessage *string `protobuf:"bytes,7,opt,name=error_message,json=errorMessage,proto3,oneof" json:"error_message,omitempty"`
	// When the account was created (for tracking age)
	CreationTime  *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=creation_time,json=creationTime,proto3,oneof" json:"creation_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateKeystoreResponse) Reset() {
	*x = CreateKeystoreResponse{}
	mi := &file_plugin_keystore_management_v1_management_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateKeystoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKeystoreResponse) ProtoMessage() {}

func (x *CreateKeystoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_keystore_management_v1_management_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKeystoreResponse.ProtoReflect.Descriptor instead.
func (*CreateKeystoreResponse) Descriptor() ([]byte, []int) {
	return file_plugin_keystore_management_v1_management_proto_rawDescGZIP(), []int{3}
}

// Deprecated: Marked as deprecated in plugin/keystore/management/v1/management.proto.
func (x *CreateKeystoreResponse) GetConfig() *v1.KeystoreInstanceConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *CreateKeystoreResponse) GetRoleManagementConfig() *ManagementConfig {
	if x != nil {
		return x.RoleManagementConfig
	}
	return nil
}

func (x *CreateKeystoreResponse) GetKeyManagementConfig() *ManagementConfig {
	if x != nil {
		return x.KeyManagementConfig
	}
	return nil
}

func (x *CreateKeystoreResponse) GetSupportedRegions() []*SupportedRegion {
	if x != nil {
		return x.SupportedRegions
	}
	return nil
}

func (x *CreateKeystoreResponse) GetStatus() KeystoreCreationStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return KeystoreCreationStatus_KEYSTORE_CREATION_STATUS_UNSPECIFIED
}

func (x *CreateKeystoreResponse) GetAccountId() string {
	if x != nil && x.AccountId != nil {
		return *x.AccountId
	}
	return ""
}

func (x *CreateKeystoreResponse) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

func (x *CreateKeystoreResponse) GetCreationTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreationTime
	}
	return nil
}

type DeleteKeystoreRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Config        *v1.KeystoreInstanceConfig `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteKeystoreRequest) Reset() {
	*x = DeleteKeystoreRequest{}
	mi := &file_plugin_keystore_management_v1_management_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteKeystoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKeystoreRequest) ProtoMessage() {}

func (x *DeleteKeystoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_keystore_management_v1_management_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKeystoreRequest.ProtoReflect.Descriptor instead.
func (*DeleteKeystoreRequest) Descriptor() ([]byte, []int) {
	return file_plugin_keystore_management_v1_management_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteKeystoreRequest) GetConfig() *v1.KeystoreInstanceConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type DeleteKeystoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteKeystoreResponse) Reset() {
	*x = DeleteKeystoreResponse{}
	mi := &file_plugin_keystore_management_v1_management_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteKeystoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKeystoreResponse) ProtoMessage() {}

func (x *DeleteKeystoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_keystore_management_v1_management_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKeystoreResponse.ProtoReflect.Descriptor instead.
func (*DeleteKeystoreResponse) Descriptor() ([]byte, []int) {
	return file_plugin_keystore_management_v1_management_proto_rawDescGZIP(), []int{5}
}

// GrantTrustRequest represents the request to grant trust to a client certificate subject pattern
// for accessing a keystore instance from the crypto layer.
// - The config field contains the authentication configuration of the role management role for the keystore instance,
// which is used to authenticate the request to grant trust.
// - The subject field contains the client certificate subject to grant trust to
// - The region field specifies the logical region for which the trust is being granted
// - The type field specifies whether to create a management or crypto role
type GrantTrustRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Config        *v1.KeystoreInstanceConfig `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	Subject       string                     `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Region        string                     `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	Type          TrustType                  `protobuf:"varint,4,opt,name=type,proto3,enum=plugin.keystore.management.v1.TrustType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrantTrustRequest) Reset() {
	*x = GrantTrustRequest{}
	mi := &file_plugin_keystore_management_v1_management_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantTrustRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantTrustRequest) ProtoMessage() {}

func (x *GrantTrustRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_keystore_management_v1_management_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantTrustRequest.ProtoReflect.Descriptor instead.
func (*GrantTrustRequest) Descriptor() ([]byte, []int) {
	return file_plugin_keystore_management_v1_management_proto_rawDescGZIP(), []int{6}
}

func (x *GrantTrustRequest) GetConfig() *v1.KeystoreInstanceConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *GrantTrustRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *GrantTrustRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *GrantTrustRequest) GetType() TrustType {
	if x != nil {
		return x.Type
	}
	return TrustType_TRUST_TYPE_UNSPECIFIED
}

// GrantTrustResponse represents the response after granting trust to a client certificate subject pattern
// for accessing a keystore instance. Returns the access data of the configured trust
type GrantTrustResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessData    *structpb.Struct       `protobuf:"bytes,1,opt,name=access_data,json=accessData,proto3" json:"access_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrantTrustResponse) Reset() {
	*x = GrantTrustResponse{}
	mi := &file_plugin_keystore_management_v1_management_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantTrustResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantTrustResponse) ProtoMessage() {}

func (x *GrantTrustResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_keystore_management_v1_management_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantTrustResponse.ProtoReflect.Descriptor instead.
func (*GrantTrustResponse) Descriptor() ([]byte, []int) {
	return file_plugin_keystore_management_v1_management_proto_rawDescGZIP(), []int{7}
}

func (x *GrantTrustResponse) GetAccessData() *structpb.Struct {
	if x != nil {
		return x.AccessData
	}
	return nil
}

// RemoveTrustRequest represents the request to remove trust for a client certificate subject pattern
// to revoke access to a keystore instance.
// - The config field contains the authentication configuration of the role management role for the keystore instance,
// which is used to authenticate the request to remove trust.
// - The access_data field contains the access data of the trust to be removed
type RemoveTrustRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Config        *v1.KeystoreInstanceConfig `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	AccessData    *structpb.Struct           `protobuf:"bytes,2,opt,name=access_data,json=accessData,proto3" json:"access_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveTrustRequest) Reset() {
	*x = RemoveTrustRequest{}
	mi := &file_plugin_keystore_management_v1_management_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveTrustRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveTrustRequest) ProtoMessage() {}

func (x *RemoveTrustRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_keystore_management_v1_management_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveTrustRequest.ProtoReflect.Descriptor instead.
func (*RemoveTrustRequest) Descriptor() ([]byte, []int) {
	return file_plugin_keystore_management_v1_management_proto_rawDescGZIP(), []int{8}
}

func (x *RemoveTrustRequest) GetConfig() *v1.KeystoreInstanceConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *RemoveTrustRequest) GetAccessData() *structpb.Struct {
	if x != nil {
		return x.AccessData
	}
	return nil
}

type RemoveTrustResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveTrustResponse) Reset() {
	*x = RemoveTrustResponse{}
	mi := &file_plugin_keystore_management_v1_management_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveTrustResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveTrustResponse) ProtoMessage() {}

func (x *RemoveTrustResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_keystore_management_v1_management_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveTrustResponse.ProtoReflect.Descriptor instead.
func (*RemoveTrustResponse) Descriptor() ([]byte, []int) {
	return file_plugin_keystore_management_v1_management_proto_rawDescGZIP(), []int{9}
}

// GetKeystoreStatusRequest represents a request to check the current status of a pending keystore.
// This is a read-only operation that does not modify any state.
type GetKeystoreStatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Account ID returned from CreateKeystore when status was PENDING_ACTIVATION
	AccountId     string `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKeystoreStatusRequest) Reset() {
	*x = GetKeystoreStatusRequest{}
	mi := &file_plugin_keystore_management_v1_management_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeystoreStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeystoreStatusRequest) ProtoMessage() {}

func (x *GetKeystoreStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_keystore_management_v1_management_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeystoreStatusRequest.ProtoReflect.Descriptor instead.
func (*GetKeystoreStatusRequest) Descriptor() ([]byte, []int) {
	return file_plugin_keystore_management_v1_management_proto_rawDescGZIP(), []int{10}
}

func (x *GetKeystoreStatusRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

// GetKeystoreStatusResponse represents the current status of a keystore creation.
// This is informational only and does not trigger any setup actions.
type GetKeystoreStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Current status: "PENDING_ACTIVATION", "ACTIVE", or "FAILED"
	// Optional field - when not set (absent), status is unknown and client should retry the request
	Status *KeystoreCreationStatus `protobuf:"varint,1,opt,name=status,proto3,enum=plugin.keystore.management.v1.KeystoreCreationStatus,oneof" json:"status,omitempty"`
	// Error message when status is "FAILED"
	// Optional field - only present when status is "FAILED"
	ErrorMessage  *string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3,oneof" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKeystoreStatusResponse) Reset() {
	*x = GetKeystoreStatusResponse{}
	mi := &file_plugin_keystore_management_v1_management_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeystoreStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeystoreStatusResponse) ProtoMessage() {}

func (x *GetKeystoreStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_keystore_management_v1_management_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeystoreStatusResponse.ProtoReflect.Descriptor instead.
func (*GetKeystoreStatusResponse) Descriptor() ([]byte, []int) {
	return file_plugin_keystore_management_v1_management_proto_rawDescGZIP(), []int{11}
}

func (x *GetKeystoreStatusResponse) GetStatus() KeystoreCreationStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return KeystoreCreationStatus_KEYSTORE_CREATION_STATUS_UNSPECIFIED
}

func (x *GetKeystoreStatusResponse) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

// FinalizeKeystoreSetupRequest represents a request to complete keystore setup.
// This should be called after GetKeystoreStatus returns "ACTIVE" to create the cloud resources.
// CMK passes back the original CreateKeystore parameters so the plugin remains stateless.
type FinalizeKeystoreSetupRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Account ID returned from CreateKeystore
	AccountId string `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	// Original parameters from CreateKeystoreRequest
	// CMK stores these when CreateKeystore returns PENDING_ACTIVATION and passes them back here
	// This allows the plugin to remain stateless - no need to cache creation parameters
	Values        *structpb.Struct `protobuf:"bytes,2,opt,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalizeKeystoreSetupRequest) Reset() {
	*x = FinalizeKeystoreSetupRequest{}
	mi := &file_plugin_keystore_management_v1_management_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizeKeystoreSetupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeKeystoreSetupRequest) ProtoMessage() {}

func (x *FinalizeKeystoreSetupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_keystore_management_v1_management_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeKeystoreSetupRequest.ProtoReflect.Descriptor instead.
func (*FinalizeKeystoreSetupRequest) Descriptor() ([]byte, []int) {
	return file_plugin_keystore_management_v1_management_proto_rawDescGZIP(), []int{12}
}

func (x *FinalizeKeystoreSetupRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *FinalizeKeystoreSetupRequest) GetValues() *structpb.Struct {
	if x != nil {
		return x.Values
	}
	return nil
}

// FinalizeKeystoreSetupResponse represents the response after finalizing keystore setup.
// Returns the full configuration with all cloud resources created.
type FinalizeKeystoreSetupResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	RoleManagementConfig *ManagementConfig      `protobuf:"bytes,1,opt,name=role_management_config,json=roleManagementConfig,proto3" json:"role_management_config,omitempty"`
	KeyManagementConfig  *ManagementConfig      `protobuf:"bytes,2,opt,name=key_management_config,json=keyManagementConfig,proto3" json:"key_management_config,omitempty"`
	SupportedRegions     []*SupportedRegion     `protobuf:"bytes,3,rep,name=supported_regions,json=supportedRegions,proto3" json:"supported_regions,omitempty"`
	// Status: "ACTIVE" on success, "FAILED" on error
	// Optional field - when not set (absent), clients should check error_message to determine success/failure
	Status *KeystoreCreationStatus `protobuf:"varint,4,opt,name=status,proto3,enum=plugin.keystore.management.v1.KeystoreCreationStatus,oneof" json:"status,omitempty"`
	// Error message if setup failed
	// Optional field - only present when status is "FAILED"
	ErrorMessage  *string `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3,oneof" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalizeKeystoreSetupResponse) Reset() {
	*x = FinalizeKeystoreSetupResponse{}
	mi := &file_plugin_keystore_management_v1_management_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizeKeystoreSetupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeKeystoreSetupResponse) ProtoMessage() {}

func (x *FinalizeKeystoreSetupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_keystore_management_v1_management_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeKeystoreSetupResponse.ProtoReflect.Descriptor instead.
func (*FinalizeKeystoreSetupResponse) Descriptor() ([]byte, []int) {
	return file_plugin_keystore_management_v1_management_proto_rawDescGZIP(), []int{13}
}

func (x *FinalizeKeystoreSetupResponse) GetRoleManagementConfig() *ManagementConfig {
	if x != nil {
		return x.RoleManagementConfig
	}
	return nil
}

func (x *FinalizeKeystoreSetupResponse) GetKeyManagementConfig() *ManagementConfig {
	if x != nil {
		return x.KeyManagementConfig
	}
	return nil
}

func (x *FinalizeKeystoreSetupResponse) GetSupportedRegions() []*SupportedRegion {
	if x != nil {
		return x.SupportedRegions
	}
	return nil
}

func (x *FinalizeKeystoreSetupResponse) GetStatus() KeystoreCreationStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return KeystoreCreationStatus_KEYSTORE_CREATION_STATUS_UNSPECIFIED
}

func (x *FinalizeKeystoreSetupResponse) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

var File_plugin_keystore_management_v1_management_proto protoreflect.FileDescriptor

const file_plugin_keystore_management_v1_management_proto_rawDesc = "" +
	"\n" +
	".plugin/keystore/management/v1/management.proto\x12\x1dplugin.keystore.management.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a&plugin/keystore/common/v1/common.proto\"L\n" +
	"\x0fSupportedRegion\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\x0etechnical_name\x18\x02 \x01(\tR\rtechnicalName\"\xa8\x01\n" +
	"\x10ManagementConfig\x12\x1f\n" +
	"\vlocality_id\x18\x01 \x01(\tR\n" +
	"localityId\x12\x1f\n" +
	"\vcommon_name\x18\x02 \x01(\tR\n" +
	"commonName\x12R\n" +
	"\vaccess_data\x18\x03 \x01(\v21.plugin.keystore.common.v1.KeystoreInstanceConfigR\n" +
	"accessData\"H\n" +
	"\x15CreateKeystoreRequest\x12/\n" +
	"\x06values\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x06values\"\xb6\x05\n" +
	"\x16CreateKeystoreResponse\x12M\n" +
	"\x06config\x18\x01 \x01(\v21.plugin.keystore.common.v1.KeystoreInstanceConfigB\x02\x18\x01R\x06config\x12e\n" +
	"\x16role_management_config\x18\x02 \x01(\v2/.plugin.keystore.management.v1.ManagementConfigR\x14roleManagementConfig\x12c\n" +
	"\x15key_management_config\x18\x03 \x01(\v2/.plugin.keystore.management.v1.ManagementConfigR\x13keyManagementConfig\x12[\n" +
	"\x11supported_regions\x18\x04 \x03(\v2..plugin.keystore.management.v1.SupportedRegionR\x10supportedRegions\x12R\n" +
	"\x06status\x18\x05 \x01(\x0e25.plugin.keystore.management.v1.KeystoreCreationStatusH\x00R\x06status\x88\x01\x01\x12\"\n" +
	"\n" +
	"account_id\x18\x06 \x01(\tH\x01R\taccountId\x88\x01\x01\x12(\n" +
	"\rerror_message\x18\a \x01(\tH\x02R\ferrorMessage\x88\x01\x01\x12D\n" +
	"\rcreation_time\x18\b \x01(\v2\x1a.google.protobuf.TimestampH\x03R\fcreationTime\x88\x01\x01B\t\n" +
	"\a_statusB\r\n" +
	"\v_account_idB\x10\n" +
	"\x0e_error_messageB\x10\n" +
	"\x0e_creation_time\"b\n" +
	"\x15DeleteKeystoreRequest\x12I\n" +
	"\x06config\x18\x01 \x01(\v21.plugin.keystore.common.v1.KeystoreInstanceConfigR\x06config\"\x18\n" +
	"\x16DeleteKeystoreResponse\"\xce\x01\n" +
	"\x11GrantTrustRequest\x12I\n" +
	"\x06config\x18\x01 \x01(\v21.plugin.keystore.common.v1.KeystoreInstanceConfigR\x06config\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x16\n" +
	"\x06region\x18\x03 \x01(\tR\x06region\x12<\n" +
	"\x04type\x18\x04 \x01(\x0e2(.plugin.keystore.management.v1.TrustTypeR\x04type\"N\n" +
	"\x12GrantTrustResponse\x128\n" +
	"\vaccess_data\x18\x01 \x01(\v2\x17.google.protobuf.StructR\n" +
	"accessData\"\x99\x01\n" +
	"\x12RemoveTrustRequest\x12I\n" +
	"\x06config\x18\x01 \x01(\v21.plugin.keystore.common.v1.KeystoreInstanceConfigR\x06config\x128\n" +
	"\vaccess_data\x18\x02 \x01(\v2\x17.google.protobuf.StructR\n" +
	"accessData\"\x15\n" +
	"\x13RemoveTrustResponse\"9\n" +
	"\x18GetKeystoreStatusRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"\xb6\x01\n" +
	"\x19GetKeystoreStatusResponse\x12R\n" +
	"\x06status\x18\x01 \x01(\x0e25.plugin.keystore.management.v1.KeystoreCreationStatusH\x00R\x06status\x88\x01\x01\x12(\n" +
	"\rerror_message\x18\x02 \x01(\tH\x01R\ferrorMessage\x88\x01\x01B\t\n" +
	"\a_statusB\x10\n" +
	"\x0e_error_message\"n\n" +
	"\x1cFinalizeKeystoreSetupRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12/\n" +
	"\x06values\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x06values\"\xe3\x03\n" +
	"\x1dFinalizeKeystoreSetupResponse\x12e\n" +
	"\x16role_management_config\x18\x01 \x01(\v2/.plugin.keystore.management.v1.ManagementConfigR\x14roleManagementConfig\x12c\n" +
	"\x15key_management_config\x18\x02 \x01(\v2/.plugin.keystore.management.v1.ManagementConfigR\x13keyManagementConfig\x12[\n" +
	"\x11supported_regions\x18\x03 \x03(\v2..plugin.keystore.management.v1.SupportedRegionR\x10supportedRegions\x12R\n" +
	"\x06status\x18\x04 \x01(\x0e25.plugin.keystore.management.v1.KeystoreCreationStatusH\x00R\x06status\x88\x01\x01\x12(\n" +
	"\rerror_message\x18\x05 \x01(\tH\x01R\ferrorMessage\x88\x01\x01B\t\n" +
	"\a_statusB\x10\n" +
	"\x0e_error_message*\xbd\x01\n" +
	"\x16KeystoreCreationStatus\x12(\n" +
	"$KEYSTORE_CREATION_STATUS_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fKEYSTORE_CREATION_STATUS_ACTIVE\x10\x01\x12/\n" +
	"+KEYSTORE_CREATION_STATUS_PENDING_ACTIVATION\x10\x02\x12#\n" +
	"\x1fKEYSTORE_CREATION_STATUS_FAILED\x10\x03*Y\n" +
	"\tTrustType\x12\x1a\n" +
	"\x16TRUST_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15TRUST_TYPE_MANAGEMENT\x10\x01\x12\x15\n" +
	"\x11TRUST_TYPE_CRYPTO\x10\x022\x97\x06\n" +
	"\x10KeystoreProvider\x12}\n" +
	"\x0eCreateKeystore\x124.plugin.keystore.management.v1.CreateKeystoreRequest\x1a5.plugin.keystore.management.v1.CreateKeystoreResponse\x12}\n" +
	"\x0eDeleteKeystore\x124.plugin.keystore.management.v1.DeleteKeystoreRequest\x1a5.plugin.keystore.management.v1.DeleteKeystoreResponse\x12q\n" +
	"\n" +
	"GrantTrust\x120.plugin.keystore.management.v1.GrantTrustRequest\x1a1.plugin.keystore.management.v1.GrantTrustResponse\x12t\n" +
	"\vRemoveTrust\x121.plugin.keystore.management.v1.RemoveTrustRequest\x1a2.plugin.keystore.management.v1.RemoveTrustResponse\x12\x86\x01\n" +
	"\x11GetKeystoreStatus\x127.plugin.keystore.management.v1.GetKeystoreStatusRequest\x1a8.plugin.keystore.management.v1.GetKeystoreStatusResponse\x12\x92\x01\n" +
	"\x15FinalizeKeystoreSetup\x12;.plugin.keystore.management.v1.FinalizeKeystoreSetupRequest\x1a<.plugin.keystore.management.v1.FinalizeKeystoreSetupResponseBPZNgithub.com/openkcm/plugin-sdk/proto/plugin/keystore/management/v1;managementv1b\x06proto3"

var (
	file_plugin_keystore_management_v1_management_proto_rawDescOnce sync.Once
	file_plugin_keystore_management_v1_management_proto_rawDescData []byte
)

func file_plugin_keystore_management_v1_management_proto_rawDescGZIP() []byte {
	file_plugin_keystore_management_v1_management_proto_rawDescOnce.Do(func() {
		file_plugin_keystore_management_v1_management_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_keystore_management_v1_management_proto_rawDesc), len(file_plugin_keystore_management_v1_management_proto_rawDesc)))
	})
	return file_plugin_keystore_management_v1_management_proto_rawDescData
}

var file_plugin_keystore_management_v1_management_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_plugin_keystore_management_v1_management_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_plugin_keystore_management_v1_management_proto_goTypes = []any{
	(KeystoreCreationStatus)(0),           // 0: plugin.keystore.management.v1.KeystoreCreationStatus
	(TrustType)(0),                        // 1: plugin.keystore.management.v1.TrustType
	(*SupportedRegion)(nil),               // 2: plugin.keystore.management.v1.SupportedRegion
	(*ManagementConfig)(nil),              // 3: plugin.keystore.management.v1.ManagementConfig
	(*CreateKeystoreRequest)(nil),         // 4: plugin.keystore.management.v1.CreateKeystoreRequest
	(*CreateKeystoreResponse)(nil),        // 5: plugin.keystore.management.v1.CreateKeystoreResponse
	(*DeleteKeystoreRequest)(nil),         // 6: plugin.keystore.management.v1.DeleteKeystoreRequest
	(*DeleteKeystoreResponse)(nil),        // 7: plugin.keystore.management.v1.DeleteKeystoreResponse
	(*GrantTrustRequest)(nil),             // 8: plugin.keystore.management.v1.GrantTrustRequest
	(*GrantTrustResponse)(nil),            // 9: plugin.keystore.management.v1.GrantTrustResponse
	(*RemoveTrustRequest)(nil),            // 10: plugin.keystore.management.v1.RemoveTrustRequest
	(*RemoveTrustResponse)(nil),           // 11: plugin.keystore.management.v1.RemoveTrustResponse
	(*GetKeystoreStatusRequest)(nil),      // 12: plugin.keystore.management.v1.GetKeystoreStatusRequest
	(*GetKeystoreStatusResponse)(nil),     // 13: plugin.keystore.management.v1.GetKeystoreStatusResponse
	(*FinalizeKeystoreSetupRequest)(nil),  // 14: plugin.keystore.management.v1.FinalizeKeystoreSetupRequest
	(*FinalizeKeystoreSetupResponse)(nil), // 15: plugin.keystore.management.v1.FinalizeKeystoreSetupResponse
	(*v1.KeystoreInstanceConfig)(nil),     // 16: plugin.keystore.common.v1.KeystoreInstanceConfig
	(*structpb.Struct)(nil),               // 17: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),         // 18: google.protobuf.Timestamp
}
var file_plugin_keystore_management_v1_management_proto_depIdxs = []int32{
	16, // 0: plugin.keystore.management.v1.ManagementConfig.access_data:type_name -> plugin.keystore.common.v1.KeystoreInstanceConfig
	17, // 1: plugin.keystore.management.v1.CreateKeystoreRequest.values:type_name -> google.protobuf.Struct
	16, // 2: plugin.keystore.management.v1.CreateKeystoreResponse.config:type_name -> plugin.keystore.common.v1.KeystoreInstanceConfig
	3,  // 3: plugin.keystore.management.v1.CreateKeystoreResponse.role_management_config:type_name -> plugin.keystore.management.v1.ManagementConfig
	3,  // 4: plugin.keystore.management.v1.CreateKeystoreResponse.key_management_config:type_name -> plugin.keystore.management.v1.ManagementConfig
	2,  // 5: plugin.keystore.management.v1.CreateKeystoreResponse.supported_regions:type_name -> plugin.keystore.management.v1.SupportedRegion
	0,  // 6: plugin.keystore.management.v1.CreateKeystoreResponse.status:type_name -> plugin.keystore.management.v1.KeystoreCreationStatus
	18, // 7: plugin.keystore.management.v1.CreateKeystoreResponse.creation_time:type_name -> google.protobuf.Timestamp
	16, // 8: plugin.keystore.management.v1.DeleteKeystoreRequest.config:type_name -> plugin.keystore.common.v1.KeystoreInstanceConfig
	16, // 9: plugin.keystore.management.v1.GrantTrustRequest.config:type_name -> plugin.keystore.common.v1.KeystoreInstanceConfig
	1,  // 10: plugin.keystore.management.v1.GrantTrustRequest.type:type_name -> plugin.keystore.management.v1.TrustType
	17, // 11: plugin.keystore.management.v1.GrantTrustResponse.access_data:type_name -> google.protobuf.Struct
	16, // 12: plugin.keystore.management.v1.RemoveTrustRequest.config:type_name -> plugin.keystore.common.v1.KeystoreInstanceConfig
	17, // 13: plugin.keystore.management.v1.RemoveTrustRequest.access_data:type_name -> google.protobuf.Struct
	0,  // 14: plugin.keystore.management.v1.GetKeystoreStatusResponse.status:type_name -> plugin.keystore.management.v1.KeystoreCreationStatus
	17, // 15: plugin.keystore.management.v1.FinalizeKeystoreSetupRequest.values:type_name -> google.protobuf.Struct
	3,  // 16: plugin.keystore.management.v1.FinalizeKeystoreSetupResponse.role_management_config:type_name -> plugin.keystore.management.v1.ManagementConfig
	3,  // 17: plugin.keystore.management.v1.FinalizeKeystoreSetupResponse.key_management_config:type_name -> plugin.keystore.management.v1.ManagementConfig
	2,  // 18: plugin.keystore.management.v1.FinalizeKeystoreSetupResponse.supported_regions:type_name -> plugin.keystore.management.v1.SupportedRegion
	0,  // 19: plugin.keystore.management.v1.FinalizeKeystoreSetupResponse.status:type_name -> plugin.keystore.management.v1.KeystoreCreationStatus
	4,  // 20: plugin.keystore.management.v1.KeystoreProvider.CreateKeystore:input_type -> plugin.keystore.management.v1.CreateKeystoreRequest
	6,  // 21: plugin.keystore.management.v1.KeystoreProvider.DeleteKeystore:input_type -> plugin.keystore.management.v1.DeleteKeystoreRequest
	8,  // 22: plugin.keystore.management.v1.KeystoreProvider.GrantTrust:input_type -> plugin.keystore.management.v1.GrantTrustRequest
	10, // 23: plugin.keystore.management.v1.KeystoreProvider.RemoveTrust:input_type -> plugin.keystore.management.v1.RemoveTrustRequest
	12, // 24: plugin.keystore.management.v1.KeystoreProvider.GetKeystoreStatus:input_type -> plugin.keystore.management.v1.GetKeystoreStatusRequest
	14, // 25: plugin.keystore.management.v1.KeystoreProvider.FinalizeKeystoreSetup:input_type -> plugin.keystore.management.v1.FinalizeKeystoreSetupRequest
	5,  // 26: plugin.keystore.management.v1.KeystoreProvider.CreateKeystore:output_type -> plugin.keystore.management.v1.CreateKeystoreResponse
	7,  // 27: plugin.keystore.management.v1.KeystoreProvider.DeleteKeystore:output_type -> plugin.keystore.management.v1.DeleteKeystoreResponse
	9,  // 28: plugin.keystore.management.v1.KeystoreProvider.GrantTrust:output_type -> plugin.keystore.management.v1.GrantTrustResponse
	11, // 29: plugin.keystore.management.v1.KeystoreProvider.RemoveTrust:output_type -> plugin.keystore.management.v1.RemoveTrustResponse
	13, // 30: plugin.keystore.management.v1.KeystoreProvider.GetKeystoreStatus:output_type -> plugin.keystore.management.v1.GetKeystoreStatusResponse
	15, // 31: plugin.keystore.management.v1.KeystoreProvider.FinalizeKeystoreSetup:output_type -> plugin.keystore.management.v1.FinalizeKeystoreSetupResponse
	26, // [26:32] is the sub-list for method output_type
	20, // [20:26] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_plugin_keystore_management_v1_management_proto_init() }
func file_plugin_keystore_management_v1_management_proto_init() {
	if File_plugin_keystore_management_v1_management_proto != nil {
		return
	}
	file_plugin_keystore_management_v1_management_proto_msgTypes[3].OneofWrappers = []any{}
	file_plugin_keystore_management_v1_management_proto_msgTypes[11].OneofWrappers = []any{}
	file_plugin_keystore_management_v1_management_proto_msgTypes[13].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_keystore_management_v1_management_proto_rawDesc), len(file_plugin_keystore_management_v1_management_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugin_keystore_management_v1_management_proto_goTypes,
		DependencyIndexes: file_plugin_keystore_management_v1_management_proto_depIdxs,
		EnumInfos:         file_plugin_keystore_management_v1_management_proto_enumTypes,
		MessageInfos:      file_plugin_keystore_management_v1_management_proto_msgTypes,
	}.Build()
	File_plugin_keystore_management_v1_management_proto = out.File
	file_plugin_keystore_management_v1_management_proto_goTypes = nil
	file_plugin_keystore_management_v1_management_proto_depIdxs = nil
}
