// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: plugin/keystore/management/v1/management.proto

package managementv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"

	v1 "github.com/openkcm/plugin-sdk/proto/plugin/keystore/common/v1"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateKeystoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        *structpb.Struct       `protobuf:"bytes,1,opt,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateKeystoreRequest) Reset() {
	*x = CreateKeystoreRequest{}
	mi := &file_plugin_keystore_management_v1_management_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateKeystoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKeystoreRequest) ProtoMessage() {}

func (x *CreateKeystoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_keystore_management_v1_management_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKeystoreRequest.ProtoReflect.Descriptor instead.
func (*CreateKeystoreRequest) Descriptor() ([]byte, []int) {
	return file_plugin_keystore_management_v1_management_proto_rawDescGZIP(), []int{0}
}

func (x *CreateKeystoreRequest) GetValues() *structpb.Struct {
	if x != nil {
		return x.Values
	}
	return nil
}

type CreateKeystoreResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Config        *v1.KeystoreInstanceConfig `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateKeystoreResponse) Reset() {
	*x = CreateKeystoreResponse{}
	mi := &file_plugin_keystore_management_v1_management_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateKeystoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKeystoreResponse) ProtoMessage() {}

func (x *CreateKeystoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_keystore_management_v1_management_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKeystoreResponse.ProtoReflect.Descriptor instead.
func (*CreateKeystoreResponse) Descriptor() ([]byte, []int) {
	return file_plugin_keystore_management_v1_management_proto_rawDescGZIP(), []int{1}
}

func (x *CreateKeystoreResponse) GetConfig() *v1.KeystoreInstanceConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type DeleteKeystoreRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Config        *v1.KeystoreInstanceConfig `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteKeystoreRequest) Reset() {
	*x = DeleteKeystoreRequest{}
	mi := &file_plugin_keystore_management_v1_management_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteKeystoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKeystoreRequest) ProtoMessage() {}

func (x *DeleteKeystoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_keystore_management_v1_management_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKeystoreRequest.ProtoReflect.Descriptor instead.
func (*DeleteKeystoreRequest) Descriptor() ([]byte, []int) {
	return file_plugin_keystore_management_v1_management_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteKeystoreRequest) GetConfig() *v1.KeystoreInstanceConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type DeleteKeystoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteKeystoreResponse) Reset() {
	*x = DeleteKeystoreResponse{}
	mi := &file_plugin_keystore_management_v1_management_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteKeystoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKeystoreResponse) ProtoMessage() {}

func (x *DeleteKeystoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_keystore_management_v1_management_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKeystoreResponse.ProtoReflect.Descriptor instead.
func (*DeleteKeystoreResponse) Descriptor() ([]byte, []int) {
	return file_plugin_keystore_management_v1_management_proto_rawDescGZIP(), []int{3}
}

var File_plugin_keystore_management_v1_management_proto protoreflect.FileDescriptor

const file_plugin_keystore_management_v1_management_proto_rawDesc = "" +
	"\n" +
	".plugin/keystore/management/v1/management.proto\x12\x1dplugin.keystore.management.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a&plugin/keystore/common/v1/common.proto\"H\n" +
	"\x15CreateKeystoreRequest\x12/\n" +
	"\x06values\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x06values\"c\n" +
	"\x16CreateKeystoreResponse\x12I\n" +
	"\x06config\x18\x01 \x01(\v21.plugin.keystore.common.v1.KeystoreInstanceConfigR\x06config\"b\n" +
	"\x15DeleteKeystoreRequest\x12I\n" +
	"\x06config\x18\x01 \x01(\v21.plugin.keystore.common.v1.KeystoreInstanceConfigR\x06config\"\x18\n" +
	"\x16DeleteKeystoreResponse2\x90\x02\n" +
	"\x10KeystoreProvider\x12}\n" +
	"\x0eCreateKeystore\x124.plugin.keystore.management.v1.CreateKeystoreRequest\x1a5.plugin.keystore.management.v1.CreateKeystoreResponse\x12}\n" +
	"\x0eDeleteKeystore\x124.plugin.keystore.management.v1.DeleteKeystoreRequest\x1a5.plugin.keystore.management.v1.DeleteKeystoreResponseB\x9b\x02\n" +
	"!com.plugin.keystore.management.v1B\x0fManagementProtoP\x01ZNgithub.com/openkcm/plugin-sdk/proto/plugin/keystore/management/v1;managementv1\xa2\x02\x03PKM\xaa\x02\x1dPlugin.Keystore.Management.V1\xca\x02\x1dPlugin\\Keystore\\Management\\V1\xe2\x02)Plugin\\Keystore\\Management\\V1\\GPBMetadata\xea\x02 Plugin::Keystore::Management::V1b\x06proto3"

var (
	file_plugin_keystore_management_v1_management_proto_rawDescOnce sync.Once
	file_plugin_keystore_management_v1_management_proto_rawDescData []byte
)

func file_plugin_keystore_management_v1_management_proto_rawDescGZIP() []byte {
	file_plugin_keystore_management_v1_management_proto_rawDescOnce.Do(func() {
		file_plugin_keystore_management_v1_management_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_keystore_management_v1_management_proto_rawDesc), len(file_plugin_keystore_management_v1_management_proto_rawDesc)))
	})
	return file_plugin_keystore_management_v1_management_proto_rawDescData
}

var file_plugin_keystore_management_v1_management_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_plugin_keystore_management_v1_management_proto_goTypes = []any{
	(*CreateKeystoreRequest)(nil),     // 0: plugin.keystore.management.v1.CreateKeystoreRequest
	(*CreateKeystoreResponse)(nil),    // 1: plugin.keystore.management.v1.CreateKeystoreResponse
	(*DeleteKeystoreRequest)(nil),     // 2: plugin.keystore.management.v1.DeleteKeystoreRequest
	(*DeleteKeystoreResponse)(nil),    // 3: plugin.keystore.management.v1.DeleteKeystoreResponse
	(*structpb.Struct)(nil),           // 4: google.protobuf.Struct
	(*v1.KeystoreInstanceConfig)(nil), // 5: plugin.keystore.common.v1.KeystoreInstanceConfig
}
var file_plugin_keystore_management_v1_management_proto_depIdxs = []int32{
	4, // 0: plugin.keystore.management.v1.CreateKeystoreRequest.values:type_name -> google.protobuf.Struct
	5, // 1: plugin.keystore.management.v1.CreateKeystoreResponse.config:type_name -> plugin.keystore.common.v1.KeystoreInstanceConfig
	5, // 2: plugin.keystore.management.v1.DeleteKeystoreRequest.config:type_name -> plugin.keystore.common.v1.KeystoreInstanceConfig
	0, // 3: plugin.keystore.management.v1.KeystoreProvider.CreateKeystore:input_type -> plugin.keystore.management.v1.CreateKeystoreRequest
	2, // 4: plugin.keystore.management.v1.KeystoreProvider.DeleteKeystore:input_type -> plugin.keystore.management.v1.DeleteKeystoreRequest
	1, // 5: plugin.keystore.management.v1.KeystoreProvider.CreateKeystore:output_type -> plugin.keystore.management.v1.CreateKeystoreResponse
	3, // 6: plugin.keystore.management.v1.KeystoreProvider.DeleteKeystore:output_type -> plugin.keystore.management.v1.DeleteKeystoreResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_plugin_keystore_management_v1_management_proto_init() }
func file_plugin_keystore_management_v1_management_proto_init() {
	if File_plugin_keystore_management_v1_management_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_keystore_management_v1_management_proto_rawDesc), len(file_plugin_keystore_management_v1_management_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugin_keystore_management_v1_management_proto_goTypes,
		DependencyIndexes: file_plugin_keystore_management_v1_management_proto_depIdxs,
		MessageInfos:      file_plugin_keystore_management_v1_management_proto_msgTypes,
	}.Build()
	File_plugin_keystore_management_v1_management_proto = out.File
	file_plugin_keystore_management_v1_management_proto_goTypes = nil
	file_plugin_keystore_management_v1_management_proto_depIdxs = nil
}
