// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: plugin/keystore/management/v1/management.proto

package managementv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KeystoreProvider_CreateKeystore_FullMethodName = "/plugin.keystore.management.v1.KeystoreProvider/CreateKeystore"
	KeystoreProvider_DeleteKeystore_FullMethodName = "/plugin.keystore.management.v1.KeystoreProvider/DeleteKeystore"
	KeystoreProvider_GrantTrust_FullMethodName     = "/plugin.keystore.management.v1.KeystoreProvider/GrantTrust"
	KeystoreProvider_RemoveTrust_FullMethodName    = "/plugin.keystore.management.v1.KeystoreProvider/RemoveTrust"
)

// KeystoreProviderClient is the client API for KeystoreProvider service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KeystoreProviderClient interface {
	// Create a new keystore instance
	CreateKeystore(ctx context.Context, in *CreateKeystoreRequest, opts ...grpc.CallOption) (*CreateKeystoreResponse, error)
	// Delete an existing keystore instance
	DeleteKeystore(ctx context.Context, in *DeleteKeystoreRequest, opts ...grpc.CallOption) (*DeleteKeystoreResponse, error)
	// Grant trust to a client certificate subject pattern for accessing the keystore instance
	GrantTrust(ctx context.Context, in *GrantTrustRequest, opts ...grpc.CallOption) (*GrantTrustResponse, error)
	// Remove trust for a client certificate subject pattern to revoke access to the keystore instance
	RemoveTrust(ctx context.Context, in *RemoveTrustRequest, opts ...grpc.CallOption) (*RemoveTrustResponse, error)
}

type keystoreProviderClient struct {
	cc grpc.ClientConnInterface
}

func NewKeystoreProviderClient(cc grpc.ClientConnInterface) KeystoreProviderClient {
	return &keystoreProviderClient{cc}
}

func (c *keystoreProviderClient) CreateKeystore(ctx context.Context, in *CreateKeystoreRequest, opts ...grpc.CallOption) (*CreateKeystoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateKeystoreResponse)
	err := c.cc.Invoke(ctx, KeystoreProvider_CreateKeystore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keystoreProviderClient) DeleteKeystore(ctx context.Context, in *DeleteKeystoreRequest, opts ...grpc.CallOption) (*DeleteKeystoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteKeystoreResponse)
	err := c.cc.Invoke(ctx, KeystoreProvider_DeleteKeystore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keystoreProviderClient) GrantTrust(ctx context.Context, in *GrantTrustRequest, opts ...grpc.CallOption) (*GrantTrustResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GrantTrustResponse)
	err := c.cc.Invoke(ctx, KeystoreProvider_GrantTrust_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keystoreProviderClient) RemoveTrust(ctx context.Context, in *RemoveTrustRequest, opts ...grpc.CallOption) (*RemoveTrustResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveTrustResponse)
	err := c.cc.Invoke(ctx, KeystoreProvider_RemoveTrust_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KeystoreProviderServer is the server API for KeystoreProvider service.
// All implementations must embed UnimplementedKeystoreProviderServer
// for forward compatibility.
type KeystoreProviderServer interface {
	// Create a new keystore instance
	CreateKeystore(context.Context, *CreateKeystoreRequest) (*CreateKeystoreResponse, error)
	// Delete an existing keystore instance
	DeleteKeystore(context.Context, *DeleteKeystoreRequest) (*DeleteKeystoreResponse, error)
	// Grant trust to a client certificate subject pattern for accessing the keystore instance
	GrantTrust(context.Context, *GrantTrustRequest) (*GrantTrustResponse, error)
	// Remove trust for a client certificate subject pattern to revoke access to the keystore instance
	RemoveTrust(context.Context, *RemoveTrustRequest) (*RemoveTrustResponse, error)
	mustEmbedUnimplementedKeystoreProviderServer()
}

// UnimplementedKeystoreProviderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKeystoreProviderServer struct{}

func (UnimplementedKeystoreProviderServer) CreateKeystore(context.Context, *CreateKeystoreRequest) (*CreateKeystoreResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateKeystore not implemented")
}
func (UnimplementedKeystoreProviderServer) DeleteKeystore(context.Context, *DeleteKeystoreRequest) (*DeleteKeystoreResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteKeystore not implemented")
}
func (UnimplementedKeystoreProviderServer) GrantTrust(context.Context, *GrantTrustRequest) (*GrantTrustResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GrantTrust not implemented")
}
func (UnimplementedKeystoreProviderServer) RemoveTrust(context.Context, *RemoveTrustRequest) (*RemoveTrustResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveTrust not implemented")
}
func (UnimplementedKeystoreProviderServer) mustEmbedUnimplementedKeystoreProviderServer() {}
func (UnimplementedKeystoreProviderServer) testEmbeddedByValue()                          {}

// UnsafeKeystoreProviderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KeystoreProviderServer will
// result in compilation errors.
type UnsafeKeystoreProviderServer interface {
	mustEmbedUnimplementedKeystoreProviderServer()
}

func RegisterKeystoreProviderServer(s grpc.ServiceRegistrar, srv KeystoreProviderServer) {
	// If the following call panics, it indicates UnimplementedKeystoreProviderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KeystoreProvider_ServiceDesc, srv)
}

func _KeystoreProvider_CreateKeystore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateKeystoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeystoreProviderServer).CreateKeystore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeystoreProvider_CreateKeystore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeystoreProviderServer).CreateKeystore(ctx, req.(*CreateKeystoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeystoreProvider_DeleteKeystore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteKeystoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeystoreProviderServer).DeleteKeystore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeystoreProvider_DeleteKeystore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeystoreProviderServer).DeleteKeystore(ctx, req.(*DeleteKeystoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeystoreProvider_GrantTrust_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrantTrustRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeystoreProviderServer).GrantTrust(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeystoreProvider_GrantTrust_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeystoreProviderServer).GrantTrust(ctx, req.(*GrantTrustRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeystoreProvider_RemoveTrust_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveTrustRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeystoreProviderServer).RemoveTrust(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeystoreProvider_RemoveTrust_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeystoreProviderServer).RemoveTrust(ctx, req.(*RemoveTrustRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KeystoreProvider_ServiceDesc is the grpc.ServiceDesc for KeystoreProvider service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KeystoreProvider_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "plugin.keystore.management.v1.KeystoreProvider",
	HandlerType: (*KeystoreProviderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateKeystore",
			Handler:    _KeystoreProvider_CreateKeystore_Handler,
		},
		{
			MethodName: "DeleteKeystore",
			Handler:    _KeystoreProvider_DeleteKeystore_Handler,
		},
		{
			MethodName: "GrantTrust",
			Handler:    _KeystoreProvider_GrantTrust_Handler,
		},
		{
			MethodName: "RemoveTrust",
			Handler:    _KeystoreProvider_RemoveTrust_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin/keystore/management/v1/management.proto",
}
