name: Labeler

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  do:
    uses: openkcm/build/.github/workflows/labeler.yaml@main
    secrets: inherit
