name: Git

on:
  pull_request:
    types: [ closed ]
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  release:
    uses: openkcm/build/.github/workflows/release.lib.yaml@main
    secrets: inherit
