name: REUSE Compliance Check

on:
  push:
    paths-ignore:
      - 'docs/**'
      - 'LICENSES/**'
      - '.releases/**'
      - '.github/**'
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@bb774aa972c2a89ff34781233d275075cbddf542 # v5
